### PR TITLE
Simplify strings term registration

### LINKED ISSUE #6072: Invalid model for string formula
59d9aad4839
~~~~
(declare-fun i4 () Int)
(declare-fun str5 () String)
(assert (= (str.++ str5 (str.from_int i4)) (str.++ (str.from_int 15) (str.++ str5 (str.from_int 1)))))
(push)
(check-sat)
(pop)
(check-sat)
~~~~
~~~~
cvc4 -q -i --check-models --strings-exp delta.out.smt2 
sat
Fatal failure within void CVC4::smt::CheckModels::checkModel(CVC4::smt::Model*, CVC4::context::CDList<CVC4::NodeTemplate<true> >*, bool) at /home/CVC4/src/smt/check_models.cpp:131
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (= (str.++ str5 (str.from_int i4)) (str.++ (str.from_int 15) (str.++ str5 (str.from_int 1))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped
~~~~

### PR DESCRIPTION
**Pull request by ajreynol**
String terms may enter into the equality engine without appearing in assertions, due to eager context-dependent simplification internal to the equality engine (--strings-eager-eval).  In rare cases, we did not catch when a new string constant appeared in the equality engine, meaning it would not be marked as relevant leading to bogus models in incremental mode.

This makes it so that proxy variables are stored in a user-context dependent manner, which impacts when terms marked as having a proxy variable are registered. 

The PR also simplifies our policies for when string terms are registered slightly.

Fixes #6072.

### CODE REVIEW

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Review by HanielB — APPROVED** [review]
LGTM too

**Comment by ajreynol** [comment]
Slight performance hit on smt-lib strings 60 second timeout, +22-74, will investigate.

**Comment by ajreynol** [comment]
It seems that eager registration for terms from internal equalities is a good idea.  I'm keeping this for now, although I've simplified the code.

The actual bug in this issue was related to how we store proxy variables.

With the updated PR, we are +2-3 (essentially noise) on SMT-LIB strings 60 second timeout.

**Pull request merged**
