### PR TITLE
Models standard

### PR DESCRIPTION
**Pull request by yoni206**
This PR relates to #4987 .
Our plan is to:
1. delete the `model` keyword
2. avoid printing extra declarations by default
3. wrap UF values with `as` expressions.

This PR does step 1, and fixes regressions accordingly.

### CODE REVIEW

**Review by ajreynol — COMMENTED** [review]
I'm not sure if we already want to update how the separation logic model is printed as well (see line 1343).

**Comment by yoni206** [comment]
IMH this is a separate issue because separation logic is not standard, but I'm fine either way.

**Review by ajreynol — APPROVED** [review]
LGTM

**Review by 4tXJ7f — CHANGES_REQUESTED** [review]
Since this is a user-facing change, we should update NEWS.

**Comment by yoni206** [comment]
Right, @4tXJ7f , thanks!
Addressed here:
https://github.com/CVC4/CVC4/pull/5415/commits/288ca59a0acd4dee03c5155a648cba3e2226de4e

**Review by 4tXJ7f — APPROVED** [review]
LGTM

**Pull request merged**
