### PR TITLE
Use thread_local instead of compiler extensions

### PR DESCRIPTION
**Pull request by 4tXJ7f**
C++11 introduced the thread_local keyword, so we don't need to use
non-standard extensions or our custom pthread extension anymore.
The behavior was previously introduced as a workaround in commit
753a072c542c1c254d7c6adbf10e091ba585ede5.

### CODE REVIEW

**Comment by timothy-king** [comment]
My rough understanding is that there are potential differences in performance between __thread and thread_local. I am not if sure if they apply to us so I am inclined to measure the difference. Here is a somewhat enlightening conversation:
https://stackoverflow.com/questions/13106049/what-is-the-performance-penalty-of-c11-thread-local-variables-in-gcc-4-8 

The hottest globals in CVC4 are thread local pointers (NodeManager and Options) so we will need to be careful. I'm not worried about other cases.

So I would recommend comparing CVC4 w/out this change around a broad spectrum of benchmarks. We could also take a look at the generated code to make sure we are not getting the initialization check.

**Comment by 4tXJ7f** [comment]
Hm, it is interesting. It looks like both GCC and Clang produce more efficient code with `__thread`:

- `thread_local`: https://godbolt.org/g/Vk9gWk
- `__thread`: https://godbolt.org/g/1B8Dnw

Maybe the best thing to do would be to change the check in `configure.ac` to simply check if `__thread` is supported and then use either that or `thread_local` but remove the pthread implementation.

By the way, the NodeManager pointer should not be affected by what's described in the StackOverflow post because we don't use it with `extern`.

**Comment by aniemetz** [comment]
> Maybe the best thing to do would be to change the check in configure.ac to simply check if __thread is supported and then use either that or thread_local but remove the pthread 
> implementation.

Agreed.

I'd still recommend a run time comparison as a sanity check.

**Comment by mpreiner** [comment]
Correct me if I am wrong, but pOptions shouldn't be a big problem since as far as I see it is only used for signal handling.

**Comment by 4tXJ7f** [comment]
Looks like you are right, Mathias. pOptions seems only to be read when printing statistics. Also, I am not sure why s_smtEngine_current is declared to be extern, it is only used in smt/smt_engine_scope.{h,cpp}.

**Comment by timothy-king** [comment]
> Also, I am not sure why s_smtEngine_current is declared to be extern, it is only used in smt/smt_engine_scope.{h,cpp}.
I am guessing it was originally cycles in the build graph between libraries. But that is just a guess.  I think that header should likely be rewritten with about 0 inlining if possible. Nothing here is speed critical. I would take a look to see if one can minimize the usage of this header outside of smt/ (and libcvc4) first. The pain point could be make distcheck.

> By the way, the NodeManager pointer should not be affected by what's described in the
> StackOverflow post because we don't use it with extern.
I would test that assumption even if it is likely true.

**Comment by 4tXJ7f** [comment]
Tim, I moved the function definitions in smt/smt_engine_scope from the header to the source file in pull request #216.

**Comment by 4tXJ7f** [comment]
Here are the benchmark results for QF_ABV (new-version = newer version of master with method definitions moved to source files, no-move = older version before the move, thread_local = this pull request):

```
   DIRECTORY |     STAT |   SLVD |    TOT |   TO |  MO |  ERR |   CPU[s] |  SPACE[MB] |
 new-version |       ok |  14945 |  15091 |  143 |   3 |    0 |  54641.4 |   322373.2 |
     no-move |       ok |  14947 |  15091 |  141 |   3 |    0 |  54524.3 |   321572.0 |
thread_local |       ok |  14949 |  15091 |  139 |   3 |    0 |  54728.0 |   318445.2 |



       DIRECTORY |                                       new-version |                                           no-move |                                      thread_local |
       BENCHMARK |     STAT  SLVD   TOT  TO MO ERR  CPU[s] SPACE[MB] |     STAT  SLVD   TOT  TO MO ERR  CPU[s] SPACE[MB] |     STAT  SLVD   TOT  TO MO ERR  CPU[s] SPACE[MB] |
        bench_ab |       ok   119   119   0  0   0     1.7     298.2 |       ok   119   119   0  0   0     1.7     301.3 |       ok   119   119   0  0   0     2.9     335.9 |
             bmc |       ok    36    39   3  0   0  1282.9    6489.3 |       ok    36    39   3  0   0  1334.8    6505.2 |       ok    36    39   3  0   0  1358.5    6481.1 |
  brummayerbiere |       ok   233   293  60  0   0 23658.9   64128.6 |       ok   234   293  59  0   0 23524.7   64587.5 |       ok   236   293  57  0   0 23408.1   64642.8 |
 brummayerbiere2 |       ok     7    22  13  2   0  4157.9   36836.5 |       ok     7    22  13  2   0  4173.9   36834.9 |       ok     7    22  13  2   0  4183.7   36748.2 |
 brummayerbiere3 |       ok    10    10   0  0   0     0.7     119.0 |       ok    10    10   0  0   0     0.5      96.6 |       ok    10    10   0  0   0     0.5      90.5 |
           btfnt |       ok     1     1   0  0   0   165.7     395.5 |       ok     1     1   0  0   0   161.6     392.8 |       ok     1     1   0  0   0   266.3     388.7 |
           calc2 |       ok    12    36  24  0   0  7454.7   11647.7 |       ok    12    36  24  0   0  7444.2   11674.6 |       ok    12    36  24  0   0  7458.9   11563.1 |
    dwp_formulas |       ok  5763  5765   2  0   0  1371.1   59158.7 |       ok  5763  5765   2  0   0  1388.5   57718.5 |       ok  5763  5765   2  0   0  1431.4   56509.3 |
             ecc |       ok    54    55   1  0   0   357.1    5118.1 |       ok    54    55   1  0   0   357.6    4985.8 |       ok    54    55   1  0   0   360.5    5133.0 |
             egt |       ok  7719  7719   0  0   0    37.8    4439.2 |       ok  7719  7719   0  0   0    37.6    4461.1 |       ok  7719  7719   0  0   0    36.2    4392.6 |
           jager |  memtime     0     2   1  1   0   352.6   14301.1 |  memtime     0     2   1  1   0   346.4   14304.0 |  memtime     0     2   1  1   0   346.5   14302.5 |
            klee |       ok   622   622   0  0   0  1978.6   45338.6 |       ok   622   622   0  0   0  1978.0   45480.0 |       ok   622   622   0  0   0  2030.7   44306.0 |
            pipe |     time     0     1   1  0   0   300.1     847.7 |     time     0     1   1  0   0   300.1     722.4 |     time     0     1   1  0   0   300.0     556.1 |
        platania |       ok   242   275  33  0   0 10668.8   22047.3 |       ok   242   275  33  0   0 10635.6   22125.5 |       ok   242   275  33  0   0 10682.7   21774.0 |
         sharing |       ok    40    40   0  0   0     0.0       0.0 |       ok    40    40   0  0   0     0.0       0.0 |       ok    40    40   0  0   0     0.0       0.0 |
             stp |       ok    35    40   5  0   0  2852.9   51153.5 |       ok    36    40   4  0   0  2839.0   51323.9 |       ok    36    40   4  0   0  2860.8   51173.6 |
     stp_samples |       ok    52    52   0  0   0     0.2      54.2 |       ok    52    52   0  0   0     0.3      57.9 |       ok    52    52   0  0   0     0.2      47.8 |
          totals |       ok 14945 15091 143  3   0 54641.4  322373.2 |       ok 14947 15091 141  3   0 54524.3  321572.0 |       ok 14949 15091 139  3   0 54728.0  318445.2 |
```

And the results for QF_BV:
```
       DIRECTORY |  STAT |   SLVD |    TOT |    TO |  MO |  ERR |     CPU[s] |   SPACE[MB] |
 log_new_version |    ok |  45495 |  49971 |  4303 |  60 |  113 |  1860015.0 |  10557246.7 |
     log_no_move |    ok |  45502 |  49971 |  4308 |  60 |  101 |  1859933.7 |  10488609.9 |
log_thread_local |    ok |  45499 |  49971 |  4280 |  60 |  132 |  1860686.8 |  10486404.0 |



               DIRECTORY |                                    log_new_version |                                        log_no_move |                                   log_thread_local |
               BENCHMARK |  STAT  SLVD   TOT   TO MO ERR    CPU[s]  SPACE[MB] |  STAT  SLVD   TOT   TO MO ERR    CPU[s]  SPACE[MB] |  STAT  SLVD   TOT   TO MO ERR    CPU[s]  SPACE[MB] |
                     asp |    ok   287   492  179 17   9   85719.7   668627.1 |    ok   288   492  176 17  11   85834.5   668485.6 |    ok   285   492  178 17  12   85898.9   667980.9 |
                bench_ab |    ok   285   285    0  0   0       0.0        0.0 |    ok   285   285    0  0   0       0.0        0.0 |    ok   285   285    0  0   0       0.0        0.0 |
                     bmc |    ok   198   201    2  0   1    2494.9    31015.4 |    ok   198   201    2  0   1    2474.2    30984.4 |    ok   198   201    2  0   1    2540.9    30934.7 |
          brummayerbiere |    ok    38    52   13  1   0    4970.3    43776.8 |    ok    38    52   13  1   0    4961.4    43328.8 |    ok    38    52   13  1   0    4946.3    43296.0 |
         brummayerbiere2 |    ok    58    65    7  0   0    3395.2    34878.8 |    ok    58    65    7  0   0    3404.2    35090.9 |    ok    58    65    6  0   1    3394.3    34858.1 |
         brummayerbiere3 |    ok    34    79   41  2   2   13723.9    94430.7 |    ok    39    79   36  2   2   13529.4    98523.0 |    ok    35    79   42  2   0   13727.5    94573.0 |
         brummayerbiere4 |    ok     9    10    0  1   0      73.4     8592.8 |    ok     9    10    0  1   0      68.5     8372.6 |    ok     9    10    0  1   0      70.3     8523.2 |
             bruttomesso |    ok   976   976    0  0   0    5656.3   109148.9 |    ok   976   976    0  0   0    5590.3   106971.4 |    ok   976   976    0  0   0    5561.6   106804.7 |
                 calypto |    ok    14    23    9  0   0    2768.3     6053.1 |    ok    14    23    9  0   0    2767.3     5939.7 |    ok    14    23    9  0   0    2773.6     6051.7 |
               challenge |  time     0     2    2  0   0     600.2     1536.9 |  time     0     2    2  0   0     600.5     1536.4 |  time     0     2    2  0   0     600.3     1548.0 |
                  check2 |    ok     6     6    0  0   0       0.0        0.0 |    ok     6     6    0  0   0       0.0        0.0 |    ok     6     6    0  0   0       0.0        0.0 |
                 crafted |    ok    21    21    0  0   0       0.0        0.0 |    ok    21    21    0  0   0       0.0        0.0 |    ok    21    21    0  0   0       0.0        0.0 |
            dwp_formulas |    ok   332   332    0  0   0       0.3        0.0 |    ok   332   332    0  0   0       0.3        0.0 |    ok   332   332    0  0   0       0.2       26.0 |
                     ecc |    ok     8     8    0  0   0       9.3      583.7 |    ok     8     8    0  0   0       9.1      578.0 |    ok     8     8    0  0   0       8.9      587.7 |
                     fft |    ok     7    23   16  0   0    5074.8     7846.7 |    ok     7    23   16  0   0    5091.8     7839.6 |    ok     7    23   15  0   1    5094.9     7731.0 |
                   float |    ok   136   213   63 13   1   29350.4   304007.8 |    ok   137   213   60 13   3   29299.2   305248.6 |    ok   136   213   61 13   3   29246.6   305198.8 |
                  galois |    ok     1     4    3  0   0     901.0     3628.3 |    ok     1     4    3  0   0     901.1     3579.3 |    ok     1     4    3  0   0     900.8     3613.1 |
                 gulwani |    ok     6     6    0  0   0      33.1      729.5 |    ok     6     6    0  0   0      27.8      721.8 |    ok     6     6    0  0   0      34.8      723.5 |
                     log |    ok    31   208  169  0   8   58683.8   164763.9 |    ok    30   208  171  0   7   58703.4   163872.2 |    ok    30   208  169  0   9   58782.2   164077.3 |
                     mcm |    ok    34   186  138  5   9   47146.2   204354.1 |    ok    33   186  147  5   1   47152.5   204064.7 |    ok    34   186  142  5   5   47131.7   203841.7 |
                    pipe |  time     0     1    1  0   0     300.2      268.1 |  time     0     1    1  0   0     300.1      272.8 |  time     0     1    1  0   0     300.1      282.1 |
                  pspace |    ok    86    86    0  0   0       0.0        0.0 |    ok    86    86    0  0   0       0.0        0.0 |    ok    86    86    0  0   0       0.0        0.0 |
                   rubik |    ok     5     7    1  0   1     865.7      989.7 |    ok     5     7    2  0   0     824.4     1013.5 |    ok     5     7    2  0   0     864.5      974.4 |
                     RWS |    ok    16    20    4  0   0    1295.0     7813.8 |    ok    16    20    4  0   0    1295.3     7871.5 |    ok    16    20    4  0   0    1295.7     7827.9 |
                    sage |    ok 26596 26607    0  0  11   20593.9  1017620.3 |    ok 26602 26607    0  0   5   20229.2   988485.1 |    ok 26605 26607    0  0   2   20433.1   990105.6 |
                   Sage2 |    ok 13756 17471 3624 20  71 1535766.2  6610581.4 |    ok 13752 17471 3629 20  70 1536568.4  6575372.5 |    ok 13752 17471 3603 20  96 1536676.0  6576286.0 |
                   spear |    ok  1689  1695    6  0   0   28460.4  1107438.8 |    ok  1689  1695    6  0   0   28257.4  1102975.9 |    ok  1690  1695    5  0   0   28322.8  1103032.6 |
                     stp |    ok     1     1    0  0   0     228.5     4744.2 |    ok     1     1    0  0   0     227.0     4738.6 |    ok     1     1    0  0   0     226.9     4743.2 |
             stp_samples |    ok   424   426    2  0   0     700.2    12621.6 |    ok   424   426    1  0   1     696.8    12392.0 |    ok   424   426    2  0   0     699.8    12380.2 |
                 tacas07 |    ok     5     5    0  0   0     390.0     1382.4 |    ok     5     5    0  0   0     391.6     1370.8 |    ok     5     5    0  0   0     406.3     1329.1 |
                   uclid |    ok   414   416    2  0   0    2954.0    86684.7 |    ok   414   416    2  0   0    2882.3    85929.3 |    ok   414   416    2  0   0    2935.3    85992.6 |
 uclid_contrib_smtcomp09 |    ok     4     7    3  0   0    1963.6     3897.9 |    ok     4     7    3  0   0    1960.0     3888.1 |    ok     4     7    3  0   0    1928.5     3886.1 |
                     uum |    ok     2     8    6  0   0    1836.5     1977.4 |    ok     2     8    6  0   0    1835.9     1952.0 |    ok     2     8    6  0   0    1836.2     1932.6 |
                     VS3 |    ok     2    11    8  1   0    2819.7    14669.1 |    ok     2    11    8  1   0    2815.9    14681.2 |    ok     2    11    6  1   2    2812.2    14667.2 |
                 wienand |    ok    14    18    4  0   0    1240.2     2582.8 |    ok    14    18    4  0   0    1234.0     2529.6 |    ok    14    18    4  0   0    1235.7     2595.0 |
                  totals |    ok 45495 49971 4303 60 113 1860015.0 10557246.7 |    ok 45502 49971 4308 60 101 1859933.7 10488609.9 |    ok 45499 49971 4280 60 132 1860686.8 10486404.0 |
```

All builds were competition builds and used the competition script to run (so for QF_BV, the portfolio build ran). The timeout was 300s. I looked at the benchmarks that timed out with one configuration but not another and the most extreme case in QF_ABV was 257s instead of a timeout; in QF_BV it was 233s instead of a timeout. Most cases however, were 280s+ instead of a timeout.

**Comment by 4tXJ7f** [comment]
I updated the pull request to use a `CVC4_THREAD_LOCAL` macro instead of `thread_local` directly because Swig (at least before version 3) is not able to deal with `thread_local` and redefining a keyword is not clean. I also moved the Swig check to `tls.h` to avoid defining and then redefining `CVC4_THREAD_LOCAL` in a different place.

**Comment by aniemetz** [comment]
LGTM

**Pull request merged**
