### PR TITLE
Performance improvements suggested by cppcheck static analyser

### PR DESCRIPTION
**Pull request by ptroja**
Tiny changes that seem semantically neutral, but are likely to marginally improve performance.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
@ptroja Did you have a chance to look into applying ClangFormat? It would be great if we could get this merged.

**Comment by ptroja** [comment]
Indeed, I tried to run ClangFormat on the modified files and it reformatted lot of the code unrelated to my changes. So I got quite puzzled: my changes seem to be consistent with the current coding style and ClangFormat appears to only obfuscate them. Am I missing something?

**Comment by 4tXJ7f** [comment]
Unfortunately, not all our files fully conform to our style yet. What we usually do is to just apply ClangFormat to the lines changed. There is an integration of ClangFormat with git that you can use. If you do `git clang-format <commit>`, it will format the diff to `<commit>`. If your branch is up-to-date with master `git clang-format master` should do the trick.

**Comment by ptroja** [comment]
Thanks for the hint! Now both of my patches seem to follow the clang-format requirements.

**Comment by 4tXJ7f** [comment]
I have manually merged this PR (see commits 788212a3783affa634dc685b6f1b086f292c2528 and e7929d2cd241d8b4974d26b9e11f1378ba30b0e7 on `master`) since there were two commits and it wasn't quite clear to me whether the "Rebase and merge" option would do the right thing. Unfortunately, it doesn't look like GitHub allows me to mark this PR as merged, so I am closing it.

Thank you for your contribution @ptroja !

**Pull request closed without merging**
