### PR TITLE
Fix not to output all warnings

### PR DESCRIPTION
**Pull request by matken11235**
I fixed following warnings:
```
/usr/local/include/cvc4/base/exception.h:130:66: warning: unused parameter 'arg' [-Wunused-parameter]
template <class T> inline void CheckArgument(bool cond, const T& arg,
                                                                 ^
/usr/local/include/cvc4/base/exception.h:131:58: warning: unused parameter 'tail' [-Wunused-parameter]
                                             const char* tail) {
                                                         ^
/usr/local/include/cvc4/base/exception.h:138:66: warning: unused parameter 'arg' [-Wunused-parameter]
template <class T> inline void CheckArgument(bool cond, const T& arg) {
                                                                 ^
/usr/local/include/cvc4/context/cdlist_forward.h:45:29: warning: unused parameter 't' [-Wunused-parameter]
  inline void operator()(T* t) const{}
                            ^
/usr/local/include/cvc4/expr/datatype.h:1089:3: warning: 'const' type qualifier on return type has no effect
      [-Wignored-qualifiers]
  const unsigned getIndex() const { return d_index; }
  ^~~~~~
```

The type of warnings corrected is below:
* -Wunused-parameter
* -Wignored-qualifiers

I used `[[gnu::unused]]` to turn off -Wunused-parameter warning.
Please refer to https://stackoverflow.com/questions/31909631/c11-style-unused-attribute-in-gcc for details.
I understand that you are using C++11, but if you use C++17 in the future, please replace `[[gnu::unused]]` with `[[maybe_unused]]`.

### CODE REVIEW

**Comment by matken11235** [comment]
Oh, the macro has already been defined.
I just pushed a commit that used it.

**Comment by matken11235** [comment]
I don't know much about the CLA, but do I have to sign it?
Please tell me how do I sign it if I should sign it.

**Comment by 4tXJ7f** [comment]
Sorry for the delay. We are currently in the process of figuring out what our CLA should say. We did have one in the past for external contributions but it is outdated. I'll keep you posted.

**Comment by 4tXJ7f** [comment]
@matken11235  Sorry for the delay. We finally settled on a process for accepting external contributions that we outlined [here](https://github.com/CVC4/CVC4/blob/master/CONTRIBUTING.md). Could you please squash your two commits and sign-off the resulting commit?

Thank you for you patience and contribution.

**Comment by matken11235** [comment]
Sorry for the late response. I'll squash the four commits and sign-off it.

**Pull request merged**
