### PR TITLE
Tptp unsat core

### PR DESCRIPTION
**Pull request by ajreynol**
This pull request enables the parser and command executor properly carry names for unsat cores independent of parser.  It also adds support for unsat core name bookkeeping for TPTP.

This leads to two improvements:

(1) cvc4 --dump-unsat-cores and --dump-unsat-cores-full now take unsat core names into account
(2) These commands also work as expected with the TPTP parser, where all assertions are named based on the TPTP input format.

### CODE REVIEW

**Comment by timothy-king** [comment]
Andy, the core idea looks reasonable. I am not sure this this interface is at quite the right abstraction for other classes  but I can see how the code got moved. (For example, why does a CommandExecutor have a CommandContext passed into doCommand that might be null or not? This feels slightly over specialized.)

I am going to un-assign myself as a reviewer. I won't have upcoming cycles to do an in-depth review that this deserves in a reasonable amount of time.

**Comment by ajreynol** [comment]
Just to clarify a few points:

- The motivation of the commit was to support unsat cores for TPTP.
- When running commands with CommandExecutor, one needs to know unsat core names, which unfortunately live in the parser.

The other alternatives to the solution I give was to move unsat core names so that they live in SmtEngine,

If we decide unsat core names live in the parser, they need to get passed to the commands that are generated by --dump-unsat-core within CommandExecutor in one way or another.  The "CommandContext" was my way of doing this.

**Comment by 4tXJ7f** [comment]
In my opinion, it would be better to store the unsat core names in the SmtEngine. This will make it easier to support check-sat-assuming/get-unsat-assumptions at the C++ API level as requested in #880. I am adding @barrettcw to the discussion.

**Comment by ajreynol** [comment]
I agree there are advantages to moving unsat core names to the SmtEngine.

Unfortunately the SMT engine is not accessible to the Parser.  So this means if we want to move unsat core names to the SMT engine we have two options as far as I can tell:
(1) Give the Parser access to the SMT engine
(2) Feed all unsat core names from the Parser to the SMT engine incrementally at the driver_unified.cpp level where both exist.

Option (2) isn't very clean in my opinion, and it would introduce some overhead in copying names.

Option (1) would add an additional dependence that didn't exist before (is there a good reason why we are keeping SmtEngine and the Parser independent?).

**Comment by barrettcw** [comment]
Can we discuss this at the meeting tomorrow?

-Clark

**Comment by ajreynol** [comment]
Sounds good.

**Comment by ajreynol** [comment]
We decided on a different design: add a "set expression name" command, moving the unsat core name map to SmtEngine. I'll close this pull request once I make another pull request for this new design.

**Comment by 4tXJ7f** [comment]
I guess we can close this since we have #1228, right?

**Comment by ajreynol** [comment]
I'll close this when #1228 is merged.

**Comment by ajreynol** [comment]
Closing this now that #1228 is merged.

**Pull request closed without merging**
