### PR TITLE
Enable BV proofs when using an eager bitblaster

### PR DESCRIPTION
**Pull request by alex-ozdemir**
Specifically:
   * Removed assertions that blocked them.
   * Made sure that only bitvectors were stored in the BV const let-map
   * Prevented true/false from being bit-blasted by the eager bitblaster

Also:
   * uncommented "no-check-proofs" from relevant tests

Tested with `make check` which (after this PR) includes 3 tests of eager bitblasting proofs.

### CODE REVIEW

**Comment by mpreiner** [comment]
This only works with bvminisat right?

**Comment by alex-ozdemir** [comment]
Yes, this only works with bvminisat.

Do you think I should leave the assertions, but change them?

**Comment by mpreiner** [comment]
We should add a check to ensure that we have the right solver. An assertion is not enough.

**Comment by alex-ozdemir** [comment]
Okay, per our offline discussion I understand what you meant by "checking",  and have modified the options handler accordingly.

**Pull request merged**
