### PR TITLE
Remove Coverity SSL certificate workaround from Travis configuration.

### PR DESCRIPTION
**Pull request by mpreiner**
The SSL certificate workaround is not needed anymore since Ubuntu Trusty can handle the new ciphers used for the Coverity SSL certificate. This also removes the requirement for sudo, however, we still have to use the VM-based virtualization environment since the container-based one only provides 4G of memory instead of 7.5G. With 4G memory clang fails and gcc gets slower since it has to swap.

### CODE REVIEW

**Comment by mpreiner** [comment]
Andres tried to compile CVC4 with a 4G memory limit and it was not successful. The startup time of the container-based environment would be much faster < 1s vs ~20s, but the memory is the problem here.

**Comment by 4tXJ7f** [comment]
Some details. I restricted virtual memory to 2GB per process (simulating 4GB RAM for two processes on Travis) using `ulimit -v` and configured CVC4 to be compiled with Clang. The compilation died on `options.cpp`, a file with almost 15k lines (roughly half of the lines seem to be `#line` pragmas).

**Comment by timothy-king** [comment]
It looks like the merge is failing on travis. (Am I reading that correctly?)

**Comment by mpreiner** [comment]
There seems to be something wrong with Pat's commit on master. The Java tests fail.

**Comment by 4tXJ7f** [comment]
Yeah, there is an issue with the Java tests, see also: https://github.com/CVC4/CVC4/pull/181#discussion_r135700486

**Pull request merged**
