### PR TITLE
Make handling of 1-constructor datatypes more uniform

### LINKED ISSUE #2054: Assertion failure in TheoryDatatypes::check
Flags: `--full-saturate-quant`
File: AUFBVDTLIA/20172804-Barrett/rec-fun-ijcar2016/wo-wdf/mutant_wo_fd_vcs_wdf/2.5-cvc4-muDot2.scala-43.smt2-2.smt2

Error:
```
(error "Assertion failure.
virtual void CVC4::theory::datatypes::TheoryDatatypes::check(CVC4::theory::Theory::Effort)
../../../../src/theory/datatypes/theory_datatypes.cpp:140:

  d_pending.empty() && d_pending_merge.empty()
")
```

### PR DESCRIPTION
**Pull request by ajreynol**
This fixes #2054.

This changes the datatypes rewriter so that testers for 1-constructor datatypes are not rewritten to true. This makes invariants for splitting and the sygus solver easier to manage..

### CODE REVIEW

**Comment by ajreynol** [comment]
This led to a small performance degradation on sygus, I'm marking "do not merge" for now.  I will revisit this PR later and send an alternate fix for #2054.

**Comment by 4tXJ7f** [comment]
It looks like you updated this PR. Has anything changed about the situation?

**Comment by ajreynol** [comment]
No, actually I wanted to update it so that I can could test it combined with another branch I am working on.  I am still undecided about whether this PR is a good idea.

**Comment by ajreynol** [comment]
I'm closing this PR for now. It's unclear whether eliminating testers for 1-constructor datatypes is a good idea.

**Pull request closed without merging**
