### PR TITLE
Fix and refactor TheoryStrings::checkFlatForms()

### PR DESCRIPTION
**Pull request by 4tXJ7f**
This commit fixes some minor (performance) issues in
`TheoryStrings::checkFlatForms()`: The `inelig` vector was initialized
with copies of the `start` element instead of all the elements before
`start` and the `else` branch of `count == asize` was looping over all
elements from `1` instead of `start + 1`. Additionally, this commit
refactors the code to be a bit more readable.

### CODE REVIEW

**Comment by ajreynol** [comment]
Let's merge https://github.com/CVC4/CVC4/pull/3181 and rebase this first.

**Comment by 4tXJ7f** [comment]
Agreed. It does look like this PR is going to improve our performance a bit (300s timeout, no fmf, `--ext-rew-prep`, `--no-re-elim`):

```
       DIRECTORY |                    refactorcheckFlatForm_master |                        refactorcheckFlatForm_pr |
       Benchmark |  Stat  Slvd   Tot   To Mo Err   Cpu[s]  Mem[MB] |  Stat  Slvd   Tot   To Mo Err   Cpu[s]  Mem[MB] |
          amazon |    ok    12    12    0  0   0      6.9    209.3 |    ok    12    12    0  0   0      6.5    217.9 |
            flat |    ok   320   600  280  0   0  84862.3 159542.5 |    ok   320   600  280  0   0  84870.4 142284.6 |
 norn-benchmarks |    ok   916  1027  110  1   0  34107.6  28119.7 |    ok   917  1027  110  0   0  34098.6  19358.1 |
         qf_slia |    ok 26209 27301 1092  0   0 424771.0 572554.2 |    ok 26235 27301 1066  0   0 415402.1 571821.2 |
            slog |    ok  3391  3391    0  0   0      0.9    102.8 |    ok  3391  3391    0  0   0      0.8    104.9 |
        __totals |    ok 30848 32331 1482  1   0 543748.6 760528.5 |    ok 30875 32331 1456  0   0 534378.3 733786.7 |
```

**Comment by ajreynol** [comment]
Can you rebase this to master now?

**Comment by 4tXJ7f** [comment]
> Can you rebase this to master now?

Done, PTAL.

**Comment by ajreynol** [comment]
Looks like some compiler errors?

**Pull request merged**
