### PR TITLE
Remove some Commands from the API.

### PR DESCRIPTION
**Pull request by abdoo8080**
This PR removes `Solver::getAssignment` command from the API as there is no way to assign names to terms in the API. It also removes `ExpandDefinitionsCommand`, an internal functionality in CVC4.

### CODE REVIEW

**Review by ajreynol — APPROVED** [review]
LGTM, assuming @aniemetz agrees.

**Comment by aniemetz** [comment]
What is the alternative for (get-assignment), then?

**Comment by aniemetz** [comment]
We might argue that `getValue` is sufficient, and that we just don't have an API command that corresponds to `(get-assignment)`. I guess I'd be fine with this but first want to hear your opinions.

**Comment by ajreynol** [comment]
The consensus from the past meetings is that expression names will not be included in the API.  This means that get-assignment will be implemented by the planned "ParserState" object, which will store a mapping between names and expressions and use calls to Solver::getValue.

**Review by aniemetz — APPROVED** [review]

**Pull request merged**
