### PR TITLE
Multi-objective optimization support

### PR DESCRIPTION
**Pull request by Ouyancheng**
Supports Lexicographic, Box and Pareto optimizations 
Added test cases for BitVectors.

### CODE REVIEW

**Review by yoni206 — COMMENTED** [review]
Thank you for adding these features.
Please split this PR to two PRs so that it is easier to review.

**Comment by Ouyancheng** [comment]
How come a 400+ line PR needs to be split? Given that a 800+ PR could be easily merged?!

**Comment by yoni206** [comment]
Please refer to the developer guide, specifically here:
https://github.com/CVC4/CVC4/wiki/Developer-Guide#how-to-break-up-large-code-reviews

These are the general guidelines, though as you say it depends on the PR. 

This PR can easily be split, and splitting it will facilitate a better and faster review.

**Comment by Ouyancheng** [comment]
> Please refer to the developer guide, specifically here:
> https://github.com/CVC4/CVC4/wiki/Developer-Guide#how-to-break-up-large-code-reviews
> 
> These are the general guidelines, though as you say it depends on the PR.
> 
> This PR can easily be split, and splitting it will facilitate a better and faster review.

Tell me how

**Comment by mpreiner** [comment]
> > Please refer to the developer guide, specifically here:
> > https://github.com/CVC4/CVC4/wiki/Developer-Guide#how-to-break-up-large-code-reviews
> > These are the general guidelines, though as you say it depends on the PR.
> > This PR can easily be split, and splitting it will facilitate a better and faster review.
> 
> Tell me how

How about a PR for each `optimize*()` method?

**Pull request closed without merging**
