### PR TITLE
Allow PBE symmetry breaking with sygus stream

### PR DESCRIPTION
**Pull request by ajreynol**
This led to an unexpected performance decrease in pLTL synthesis benchmarks.

There is no reason to disable this kind of symmetry breaking when sygus-stream is enabled.

### CODE REVIEW

**Comment by HanielB** [comment]
And why are we disabling PBE itself in this case?

**Comment by ajreynol** [comment]
Since PBE (decision tree learning) shouldnt be applied with sygus-stream (or otherwise many similar decision trees would be generated).

**Comment by HanielB** [comment]
Please add a comment saying that in the point where you disable PBE. Also probably best to disable Unif+PI as well.

**Comment by ajreynol** [comment]
sygusUnif includes Unif+PI.  We do have comments talking about "basic sygus" already:  https://github.com/CVC4/CVC4/blob/master/src/smt/smt_engine.cpp#L2004

**Comment by ajreynol** [comment]
Actually, nvm about SyGuS+PI, I've added code to disable this now, good catch.

**Pull request merged**
