### PR TITLE
Optimizations for Theory::theoryOf

### PR DESCRIPTION
**Pull request by ajreynol**
These methods commonly take 10-15% of runtime.  This PR caches the result of this method. It also removes traces from the method, which can contribute around 2% of runtime on trace enabled builds (even when the trace is disabled).

### CODE REVIEW

**Comment by barrettcw** [comment]
Have you checked that this actually improves performance?  How much?

**Comment by HanielB** [comment]
If the trace overhead is restricted to trace enabled builds, which are not what is supposed to be used in non-developer settings, I don't think we should remove them.

**Comment by ajreynol** [comment]
For most Facebook benchmarks, my profiling says this method is 12%, now it is 2% after this PR.  I did confirm a roughly 10% performance improvement on the small set I've been testing in runtime on my machine.

I should also note that https://github.com/CVC4/CVC4/pull/5875 is tackling the problem the other direction (much fewer calls to Theory::theoryOf after that PR).

**Comment by HanielB** [comment]
Evaluation on SMT-LIB, 120s timeout, shows that it hurts more than it helps
```   
   DIRECTORY |                                                   master |                                                    branch |
   Benchmark |  Stat   Slvd    Tot    To Mo    Err    Cpu[s]    Mem[MB] |  Stat   Slvd    Tot    To  Mo    Err    Cpu[s]    Mem[MB] |
         ABV |    ok     17    169     0  0      0       1.5      206.4 |    ok     17    169     0   0      0       1.4      199.7 |
       ABVFP |    ee      0     30     0  0     30       0.0        0.0 |    ee      0     30     0   0     30       0.0        0.0 |
    ABVFPLRA |    ee      0     75     0  0     75       0.0        0.0 |    ee      0     75     0   0     75       0.0        0.0 |
        ALIA |    ok     35     42     0  0      0       1.8      175.9 |    ok     35     42     0   0      0       1.8      151.7 |
  AUFBVDTLIA |    ok    411   1708   864  0      0  103829.3   491404.0 |    ok    411   1708   866   0      0  104070.0   510468.0 |
  AUFBVDTNIA |    ok      0      1     0  0      0       0.0        0.0 |    ok      0      1     0   0      0       0.0        0.0 |
    AUFDTLIA |    ok    635    728     0  0      0       0.1        0.0 |    ok    635    728     0   0      0       0.0        0.0 |
   AUFDTLIRA |    ee  10519  12196   120  0    519   15150.6    75060.0 |    ee  10522  12196   118   0    519   14763.5    71427.0 |
   AUFDTNIRA |    ok    327    471    73  0      0    8823.8   132021.1 |    ok    327    471    73   0      0    8817.3   132719.6 |
 AUFFPDTLIRA |    ee      0    154     0  0    154       0.0        0.0 |    ee      0    154     0   0    154       0.0        0.0 |
 AUFFPDTNIRA |    ee      0     13     0  0     13       0.0        0.0 |    ee      0     13     0   0     13       0.0        0.0 |
      AUFLIA |    ok   2028   3276   435  0      0   53709.7   302908.4 |    ok   2027   3276   427   0      0   52801.5   329329.8 |
     AUFLIRA |    ok  19740  20011   117  0      0   17545.8    51089.4 |    ok  19741  20011   116   0      0   15014.3    46977.5 |
      AUFNIA |    ok      0      3     0  0      0       0.0        0.0 |    ok      0      3     0   0      0       0.0        0.0 |
     AUFNIRA |    ok   1037   1480   396  0      0   48241.8   120222.0 |    ok   1034   1480   399   0      0   48335.4   120192.9 |
          BV |    ok   5464   5846   382  0      0   48247.0   293235.5 |    ok   5466   5846   380   0      0   48156.1   292662.7 |
        BVFP |    ee      0    224     0  0    224       0.0       10.8 |    ee      0    224     0   0    224       0.0        0.0 |
     BVFPLRA |    ee      0    185     0  0    185       0.0       10.8 |    ee      0    185     0   0    185       0.0        0.0 |
          FP |    ee      0   2484     0  0   2484       0.0      417.1 |    ee      0   2484     0   0   2484       0.0        0.0 |
       FPLRA |    ee      0     27     0  0     27       0.0        0.0 |    ee      0     27     0   0     27       0.0        0.0 |
         LIA |    ok    579    607    28  0      0    3569.3     8260.6 |    ok    579    607    28   0      0    3569.3     8349.5 |
         LRA |    ok   1886   2419   533  0      0   65659.3    53613.3 |    ok   1885   2419   534   0      0   65726.9    55091.6 |
         NIA |    ok     18     20     2  0      0     334.8      260.2 |    ok     18     20     2   0      0     333.1      267.1 |
         NRA |    ok   3782   3813    26  0      0    3147.6     6633.7 |    ok   3782   3813    26   0      0    3149.1     6566.2 |
      QF_ABV |    ok  14503  15084   577  4      0  109866.0   557592.2 |    ok  14495  15084   585   4      0  110830.5   556323.6 |
    QF_ABVFP |    ee      0  18093     0  0  18093       0.0     4587.7 |    ee      0  18093     0   0  18093       0.0        0.0 |
 QF_ABVFPLRA |    ee      0     74     0  0     74       0.0        0.0 |    ee      0     74     0   0     74       0.0        0.0 |
     QF_ALIA |    ok    123    126     3  0      0    1405.6     5996.0 |    ok    123    126     3   0      0    1442.9     6375.1 |
     QF_ANIA |    ok     82     95    13  0      0    2369.1     6968.0 |    ok     82     95    13   0      0    2367.5     7090.3 |
    QF_AUFBV |    ok     32     56    24  0      0    2895.3    46444.5 |    ok     32     56    24   0      0    2897.0    46742.3 |
   QF_AUFLIA |    ok   1301   1303     2  0      0    1179.6     8818.4 |    ok   1302   1303     1   0      0    1113.3     8206.7 |
   QF_AUFNIA |    ok      8     17     9  0      0    1164.3     2192.1 |    ok      8     17     9   0      0    1163.3     2313.8 |
       QF_AX |    ok    551    551     0  0      0     616.4     4192.0 |    ok    551    551     0   0      0     586.6     3899.8 |
       QF_BV |    ok  37387  41713  4308 18      0  637935.9  5583286.3 |    ok  37385  41713  4312  16      0  637996.5  5580425.2 |
     QF_BVFP |    ee      0  17231     0  0  17231       0.0     3678.8 |    ee      0  17231     0   0  17231       0.0      553.2 |
  QF_BVFPLRA |    ee      0    168     0  0    168       0.0       43.0 |    ee      0    168     0   0    168       0.0        0.0 |
       QF_DT |    ok   8000   8000     0  0      0      33.0      277.2 |    ok   8000   8000     0   0      0      37.2      284.6 |
       QF_FP |    ee      0  40318     0  0  40318       0.0     8451.5 |    ee      0  40318     0   0  40318       0.0       10.7 |
    QF_FPLRA |    ee      0     57     0  0     57       0.0        0.0 |    ee      0     57     0   0     57       0.0        0.0 |
      QF_IDL |    ok   1437   2193   756  0      0  109966.2   474487.4 |    ok   1436   2193   757   0      0  110487.8   490608.1 |
      QF_LIA |    ok   3319   6947  3628  0      0  461935.6  2554864.7 |    ok   3314   6947  3633   0      0  462022.1  2577461.8 |
     QF_LIRA |    ok      5      7     2  0      0     255.1      977.5 |    ok      5      7     2   0      0     255.1      930.3 |
      QF_LRA |    ok   1357   1648   291  0      0   50219.2   167290.8 |    ok   1350   1648   298   0      0   50574.7   171406.0 |
      QF_NIA |    ok   8554  23876  8075  0      0 1164423.9  1752344.7 |    ok   8542  23876  8106   0      0 1168927.0  1843125.1 |
     QF_NIRA |    ok      1      3     2  0      0     240.1      925.5 |    ok      1      3     2   0      0     240.2     1007.7 |
      QF_NRA |    ok   8423  11489  2854  2      0  363813.4   719773.4 |    ok   8418  11489  2855   2      0  363850.2   761727.4 |
      QF_RDL |    ok    195    255    60  0      0    9847.4    25340.0 |    ok    195    255    60   0      0    9897.2    25937.9 |
        QF_S |    ee   1028   2319     0  0   1291       6.8     1187.8 |    ee   1028   2319     0   0   1291       6.9      672.9 |
     QF_SLIA |    ee  48079  67584   339  0  19166   42910.0   186559.3 |    ee  48078  67584   339   0  19167   42634.9   131231.7 |
       QF_UF |    ok   7426   7457    31  0      0    8223.4   106410.5 |    ok   7427   7457    30   0      0    8074.3   105158.5 |
     QF_UFBV |    ok   1190   1234    44  0      0   10218.4   107361.1 |    ok   1189   1234    45   0      0   10901.5   112671.3 |
     QF_UFFP |    ee      0      2     0  0      2       0.0        0.0 |    ee      0      2     0   0      2       0.0        0.0 |
    QF_UFIDL |    ok    353    428    75  0      0   11906.1    19154.7 |    ok    356    428    72   0      0   11729.9    19848.7 |
    QF_UFLIA |    ok    581    583     2  0      0    1072.5     7989.0 |    ok    581    583     2   0      0    1053.3     8041.0 |
    QF_UFLRA |    ok   1272   1284    12  0      0    2204.8    78691.4 |    ok   1272   1284    12   0      0    2209.6    81347.7 |
    QF_UFNIA |    ok    433    478    11  0      0    1396.4     4949.7 |    ok    433    478    11   0      0    1394.9     5229.3 |
    QF_UFNRA |    ok     15     37    22  0      0    2801.2     5195.2 |    ok     15     37    22   0      0    2815.9     5348.9 |
          UF |    ok   3228   7668  3699  0      0  447731.3   972912.1 |    ok   3223   7668  3701   0      0  448301.8   869815.9 |
        UFBV |    ok     55    121     4  0      0    1487.8    29025.6 |    ok     55    121     4   0      0    1466.0    28946.7 |
        UFDT |    ok   2114   4527  2034  0      0  245875.6   568131.6 |    ok   2115   4527  2035   0      0  246036.3   539774.9 |
     UFDTLIA |    ok     76    327   240  0      0   29133.9    81738.9 |    ok     75    327   241   0      0   29207.6    91930.2 |
    UFDTLIRA |    ee   8328  10743    18  0    595    2386.4    29648.9 |    ee   8326  10743    20   0    595    2571.7    25838.9 |
     UFDTNIA |    ok      1      1     0  0      0       0.4       32.1 |    ok      1      1     0   0      0       0.2       32.4 |
    UFDTNIRA |    ok   1625   1839    86  0      0   10553.7   269016.3 |    ok   1622   1839    89   0      0   10920.5   271396.5 |
  UFFPDTLIRA |    ee      0    933     0  0    933       1.4      729.9 |    ee      0    933     0   0    933       0.0       11.3 |
  UFFPDTNIRA |    ee      0     21     0  0     21       0.3       33.5 |    ee      0     21     0   0     21       0.0        2.4 |
       UFIDL |    ok     56     68     5  0      0     601.6     2069.4 |    ok     56     68     5   0      0     601.5     2179.5 |
       UFLIA |    ok   7402  10137  2020  0      0  249582.7   724204.4 |    ok   7401  10137  2016   0      0  248636.4   745430.9 |
       UFLRA |    ok     10     15     0  0      0       0.1       24.6 |    ok     10     15     0   0      0       0.0        0.0 |
       UFNIA |    ok   5673  13509  2754  0      0  360427.3  3271018.2 |    ok   5582  13509  2682 166      0  354982.7  3350603.9 |
    __totals |    ee 220701 376601 34976 24 101660 4714950.6 19930145.1 |    ee 220563 376601 34955 188 101661 4712974.7 20054346.4 |```

**Comment by mpreiner** [comment]
Hard to compare with errors and memory outs. Maybe try to compare on commonly solved benchmarks with `--show-common`.

**Comment by mpreiner** [comment]
But still quite a difference in number of solved.

**Comment by HanielB** [comment]
On commonly solved the branch is 0.08% slower.

**Comment by ajreynol** [comment]
I'm happy to close this.  Will reevaluate the bottlenecks on the Facebook challenge benchmarks, my impression is that the reductions in the # of calls to TheoryOf make this no longer necessary.

**Pull request closed without merging**
