### PR TITLE
[CVC Parser] Add support for regular expressions

### PR DESCRIPTION
**Pull request by 4tXJ7f**
This commit adds support for regular expressions in the CVC parser along
with a simple regression that illustrates and tests the use of the
regular expression operators.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Any opinions on the syntax?

cc @barrettcw @tinelli

**Comment by 4tXJ7f** [comment]
We've discussed this offline during last week's meeting and we've decided that the syntax is OK for now and that we can add syntactic sugar if needed later.

**Comment by ajreynol** [comment]
Regarding syntax, `STRING_IN_REGEXP` might be better as infix to be more in line with sets membership (infix `IS_IN`).  Otherwise, I agree the syntax is fine for now.

**Comment by 4tXJ7f** [comment]
I've overloaded `IS_IN` to be `STRING_IN_REGEXP` for non-sets. PTAL and let me know what you think. Do you prefer a separate keyword for the operator?

**Pull request merged**
