### PR TITLE
Floating point infrastructure

### PR DESCRIPTION
**Pull request by martin-cs**
I think this is the complete infrastructure required to add a floating-point solver, but I am still in the process of checking it.

Outstanding issues:
1. What should the copyright assignment say?
2. The are a few instructions that I didn't know how to parse.
3. I need to check if there are any updates to the theory that need to be encorporated.

### CODE REVIEW

**Comment by martin-neuhaeusser** [comment]
What is the status of this PR? 
It seems parts of the code have made it into the master branch. Are there any plans to complete support for FP in CVC4? It seems that a substantial amount of work has already been done - but whenever a floating-point problem is fed to CVC4, it aborts with an unimplemented exception.

In "An Automatable Formal Semantics for IEEE-754 Floating-Point Arithmetic" (from Nov. 2014), CVC4 is listed as one of the solvers that offer support for that theory (see Sec. 6). So it seems that some time back this worked. Does anyone have a clue how this can be enabled?

**Comment by martin-cs** [comment]
On Tue, 2017-01-31 at 01:16 -0800, Martin R. Neuhäußer wrote:
> What is the status of this PR? 
Stalled; my fault.

> It seems parts of the code have made it into the master branch.
Yes.

>  Are there any plans to complete support for FP in CVC4?
Yes.

>  It seems that a substantial amount of work has already been done - but whenever a floating-point problem is fed to CVC4, it aborts with an unimplemented exception.
The symfpu branch in my repository should handle most operations.

> In "An Automatable Formal Semantics for IEEE-754 Floating-Point Arithmetic" (from Nov. 2014), CVC4 is listed as one of the solvers that offer support for that theory (see Sec. 6).
Yes; there was a prototype back then.  That's what my work situation has
done to progress :-(

>  So it seems that some time back this worked. Does anyone have a clue how this can be enabled?
You need my branch.

Sorry for the lag; working at a partner site.  Full response personally
later.

Cheers,
 - Martin

**Comment by johndoe888** [comment]
Great. I will try your symfpu branch right away.

**Comment by mpreiner** [comment]
This code is already merged into master.

**Pull request closed without merging**
