### PR TITLE
Refactor parser to define fewer tokens for symbols

### PR DESCRIPTION
**Pull request by 4tXJ7f**
For some function symbols (`*`, `<`, etc.), we used tokens instead of
handling them like other function symbols. As far as I can tell, this is
a leftover from a design change that occurred a long time ago but was
not applied to all existing function symbols. Having the function
symbols as tokens is worse because you have to be careful to disable
them when a theory is not in use and we were not doing this properly in
multiple instances (see issue #2918), so we couldn't do for example
`(define-const * Bool)` even when no arithmetic theory was active. In
the current design, we define function symbols using
`Smt2::addOperator()` depending on the active theories.

This commit makes multiple changes related to that:
- It removes `builtinOp` from Smt2.g in favor of defining all operators
  in `Smt2` and moves the code that deals with some exceptional cases to
  the normal function application parsing code.
- For indexed operators, it introduces a similar mechanism via
  `addIndexedOperator()` and removes all the corresponding parsing cases
  from Smt2.g, replacing them with `mkIndexedOperator()` which takes as an
  input a name and the integer arguments to create an `OpTerm`
  corresponding to the indexed operator.
- For constants (e.g. `re.allchar`), it uses `defineVar()` to defines
  the expression that the consts correspond to.
- For indexed constants (e.g. `(_ +oo 8 24)`), it introduces a new
  method `Smt2::mkIndexedConstant()` that takes as an input the name of
  the constant and the integer parameters and returns a `Term`
  corresponding to the constant.
- Some of the regressions were broken by the stricter checking of
  defined symbols, e.g. multiplication would parse regardless of the
  logic.
- Several fixes to which operators are allowed in strict mode.

Overall, this commit moves logic out of the parser and uses `Term`s and
`OpTerm`s in some more places than before.

### CODE REVIEW

**Comment by ajreynol** [comment]
Assuming that the performance is as good or better than before, these changes look really great to me.  They will make some of the required refactoring of function applications in Smt2.g much easier.

Do you think these changes warrant a run to check performance?

**Comment by ajreynol** [comment]
Any updates on this?  Where do we stand on performance at this point?

**Comment by 4tXJ7f** [comment]
When I measured it, the performance overhead was roughly 3% (parsing only).

**Comment by ajreynol** [comment]
I think I'm in favor of merging this, even given the slight hit in performance, I think it will be helpful in the long run for improving the smt2 parser.

**Comment by 4tXJ7f** [comment]
I have resolved the merge conflict.

For the record, here are the results that show the 3% difference (120s timeout, `--parse-only`):
```
  DIRECTORY |                                          master |                                          pr2936 |
  Benchmark |  Stat Slvd    Tot To Mo    Err  Cpu[s]  Mem[MB] |  Stat Slvd    Tot To Mo    Err  Cpu[s]  Mem[MB] |
      ABVFP |    ee    0      1  0  0      1     0.0      2.2 |    ee    0      1  0  0      1     0.0      0.0 |
       ALIA |    ee    0     42  0  0     42     0.1     37.5 |    ee    0     42  0  0     42     0.7      0.0 |
 AUFBVDTLIA |    ee    0   1709  0  0   1709     0.4     57.4 |    ee    0   1709  0  0   1709     3.2    262.8 |
   AUFDTLIA |    ee    0    728  0  0    728     0.2     14.6 |    ee    0    728  0  0    728     0.0      0.0 |
     AUFLIA |    ee    0   3276  0  0   3276     1.9     60.7 |    ee    0   3276  0  0   3276     3.0    112.8 |
    AUFLIRA |    ee    0  20011  0  0  20011     0.1      0.0 |    ee    0  20011  0  0  20011     0.1      0.0 |
     AUFNIA |    ee    0      3  0  0      3     0.0      0.0 |    ee    0      3  0  0      3     0.0      0.0 |
    AUFNIRA |    ee    0   1480  0  0   1480     0.0      0.0 |    ee    0   1480  0  0   1480     0.0      0.0 |
         BV |    ee    0   5751  0  0   5751     2.3    167.4 |    ee    0   5751  0  0   5751     2.5    165.6 |
       BVFP |    ee    0     24  0  0     24     0.0      0.0 |    ee    0     24  0  0     24     0.0      0.0 |
         FP |    ee    0     61  0  0     61     0.0      0.0 |    ee    0     61  0  0     61     0.0      0.0 |
        LIA |    ee    0    388  0  0    388     0.0      0.0 |    ee    0    388  0  0    388     0.0      0.0 |
        LRA |    ee    0   2419  0  0   2419     0.0      0.0 |    ee    0   2419  0  0   2419     0.0      0.0 |
        NIA |    ee    0     14  0  0     14     0.0      0.0 |    ee    0     14  0  0     14     0.0      0.0 |
        NRA |    ee    0   3813  0  0   3813     0.0      0.0 |    ee    0   3813  0  0   3813     0.0      0.0 |
     QF_ABV |    ee    0  15066  0  0  15066   885.9  32465.2 |    ee    0  15066  0  0  15066   915.3  32593.0 |
   QF_ABVFP |    ee    0  18129  0  0  18129    12.6    869.6 |    ee    0  18129  0  0  18129    10.4    875.7 |
    QF_ALIA |    ee    0    139  0  0    139     0.1      8.7 |    ee    0    139  0  0    139     0.1      8.4 |
    QF_ANIA |    ee    0      8  0  0      8    68.0    254.1 |    ee    0      8  0  0      8    68.0    252.4 |
   QF_AUFBV |    ee    0     31  0  0     31     0.3     28.5 |    ee    0     31  0  0     31     0.3     28.2 |
  QF_AUFLIA |    ee    0   1303  0  0   1303     0.0      0.0 |    ee    0   1303  0  0   1303     0.0      0.0 |
  QF_AUFNIA |    ee    0     17  0  0     17     1.6     89.7 |    ee    0     17  0  0     17     1.6     80.1 |
      QF_AX |    ee    0    551  0  0    551     0.0      0.0 |    ee    0    551  0  0    551     0.0      0.0 |
      QF_BV |    ee    0  40102  0  0  40102 11078.9 403041.3 |    ee    0  40102  0  0  40102 11360.7 384928.4 |
    QF_BVFP |    ee    0  17215  0  0  17215     0.0      0.0 |    ee    0  17215  0  0  17215     0.0      0.0 |
      QF_DT |    ee    0   8000  0  0   8000    31.7    133.8 |    ee    0   8000  0  0   8000    33.9    133.9 |
      QF_FP |    ee    0  40300  0  0  40300     0.3     20.3 |    ee    0  40300  0  0  40300     0.2     20.5 |
     QF_IDL |    ee    0   2193  0  0   2193  1496.3  54121.6 |    ee    0   2193  0  0   2193  1550.6  54173.8 |
     QF_LIA |    ee    0   6947  0  0   6947   898.1  55684.6 |    ee    0   6947  0  0   6947   950.8  56616.2 |
    QF_LIRA |    ee    0      7  0  0      7     0.5     51.2 |    ee    0      7  0  0      7     0.5     50.5 |
     QF_LRA |    ee    0   1649  0  0   1649   782.1  12511.2 |    ee    0   1649  0  0   1649   834.7  12634.4 |
     QF_NIA |    ee    0  23876  0  0  23876   958.4  29082.0 |    ee    0  23876  0  0  23876  1013.1  29838.8 |
    QF_NIRA |    ee    0      3  0  0      3     0.3     21.3 |    ee    0      3  0  0      3     0.3     21.9 |
     QF_NRA |    ee    0  11489  0  0  11489   680.0  19619.2 |    ee    0  11489  0  0  11489   690.3  19773.6 |
     QF_RDL |    ee    0    255  0  0    255    44.3   3054.4 |    ee    0    255  0  0    255    47.1   3041.4 |
      QF_UF |    ee    0   7457  0  0   7457   455.3   7356.9 |    ee    0   7457  0  0   7457   491.5   7646.9 |
    QF_UFBV |    ee    0   1224  0  0   1224   136.9   6390.3 |    ee    0   1224  0  0   1224   142.2   6497.4 |
   QF_UFIDL |    ee    0    428  0  0    428     6.5    806.9 |    ee    0    428  0  0    428     7.7    836.1 |
   QF_UFLIA |    ee    0    583  0  0    583     0.0      0.0 |    ee    0    583  0  0    583     0.0      0.0 |
   QF_UFLRA |    ee    0   1284  0  0   1284   896.8  20822.9 |    ee    0   1284  0  0   1284   904.7  20806.3 |
   QF_UFNIA |    ee    0      7  0  0      7     0.0      0.0 |    ee    0      7  0  0      7     0.0      0.0 |
   QF_UFNRA |    ee    0     36  0  0     36     0.5      0.0 |    ee    0     36  0  0     36     0.3      0.0 |
         UF |    ee    0   7562  0  0   7562     6.4    334.6 |    ee    0   7562  0  0   7562     3.2    209.8 |
       UFBV |    ee    0    200  0  0    200   224.0   1339.0 |    ee    0    200  0  0    200   225.2   1338.0 |
       UFDT |    ee    0   4527  0  0   4527     3.7    221.1 |    ee    0   4527  0  0   4527     2.4    169.6 |
    UFDTLIA |    ee    0    303  0  0    303     0.0      0.0 |    ee    0    303  0  0    303     0.0      0.0 |
      UFIDL |    ee    0     68  0  0     68     0.1      0.0 |    ee    0     68  0  0     68     0.0      0.0 |
      UFLIA |    ee    0  10137  0  0  10137     3.2    160.8 |    ee    0  10137  0  0  10137     3.2    160.2 |
      UFLRA |    ee    0     15  0  0     15     0.0      0.0 |    ee    0     15  0  0     15     0.0      0.0 |
      UFNIA |    ee    0   3308  0  0   3308   275.3  14558.9 |    ee    0   3308  0  0   3308   291.1  15047.3 |
   __totals |    ee    0 264139  0  0 264139 18953.0 663387.9 |    ee    0 264139  0  0 264139 19558.8 648324.0 |
```

Note: the errors are because there is no output due to `--parse-only`.

**Pull request merged**
