### PR TITLE
Simplify preprocessing

### PR DESCRIPTION
**Pull request by ajreynol**
This simplifies preprocessing so that the only call to theory-preprocess and ite-removal is at the very end.  (One exception is `early-theory-pp` which is used by default in combination with `ite-simp` to maintain the performance on QF_LIA/nec).

This is in preparation for making theory preprocessing happen lazily, post-CNF conversion.

@HanielB has done SMT-LIB performance runs, see below.

### CODE REVIEW

**Comment by HanielB** [comment]
Running on the Barrett cluster with 60s timeout on all of non-incremental SMT-LIB:
```   DIRECTORY |                                                   master |                                                   branch |
   Benchmark |  Stat   Slvd    Tot    To Mo    Err    Cpu[s]    Mem[MB] |  Stat   Slvd    Tot    To Mo    Err    Cpu[s]    Mem[MB] |
         ABV |    ok     17    169     0  0      0       1.6      211.4 |    ok     17    169     0  0      0       1.5      195.7 |
       ABVFP |    ee      0     30     0  0     30       0.0        0.0 |    ee      0     30     0  0     30       0.0        0.0 |
    ABVFPLRA |    ee      0     75     0  0     75       0.0        0.0 |    ee      0     75     0  0     75       0.0        0.0 |
        ALIA |    ok     35     42     0  0      0       1.8      100.8 |    ok     35     42     0  0      0       1.7      100.0 |
  AUFBVDTLIA |    ok    412   1708   865  0      0   52077.2   373352.2 |    ok    412   1708   865  0      0   52076.9   375064.7 |
  AUFBVDTNIA |    ok      0      1     0  0      0       0.0        0.0 |    ok      0      1     0  0      0       0.0        0.0 |
    AUFDTLIA |    ok    635    728     0  0      0       0.0        0.0 |    ok    635    728     0  0      0       0.0        0.0 |
   AUFDTLIRA |    ee  10317  12196   122  0    519    7638.1    51630.7 |    ee  10317  12196   122  0    519    7659.4    53634.0 |
   AUFDTNIRA |    ok    325    471    74  0      0    4520.0    93549.4 |    ok    325    471    74  0      0    4525.5    93681.0 |
 AUFFPDTLIRA |    ee      0    154     0  0    154       0.0        0.0 |    ee      0    154     0  0    154       0.0        0.0 |
 AUFFPDTNIRA |    ee      0     13     0  0     13       0.0        0.0 |    ee      0     13     0  0     13       0.0        0.0 |
      AUFLIA |    ok   2027   3276   430  0      0   26994.9   206881.0 |    ok   2027   3276   430  0      0   26988.6   206310.9 |
     AUFLIRA |    ok  19733  20011   118  0      0    7923.5    31275.9 |    ok  19734  20011   117  0      0    7910.9    31467.1 |
      AUFNIA |    ok      0      3     0  0      0       0.0        0.0 |    ok      0      3     0  0      0       0.0        0.0 |
     AUFNIRA |    ok   1033   1480   400  0      0   24317.4    88429.8 |    ok   1033   1480   400  0      0   24319.3    88295.4 |
          BV |    ok   5448   5846   398  0      0   25450.5   253819.7 |    ok   5447   5846   399  0      0   25516.3   246297.5 |
        BVFP |    ee      0    224     0  0    224       0.0        0.0 |    ee      0    224     0  0    224       0.0        0.0 |
     BVFPLRA |    ee      0    185     0  0    185       0.0        0.0 |    ee      0    185     0  0    185       0.0        0.0 |
          FP |    ee      0   2484     0  0   2484       0.0        0.0 |    ee      0   2484     0  0   2484       0.0        0.0 |
       FPLRA |    ee      0     27     0  0     27       0.0        0.0 |    ee      0     27     0  0     27       0.0        0.0 |
         LIA |    ok    576    607    31  0      0    1911.4     4901.6 |    ok    576    607    31  0      0    1912.9     5334.9 |
         LRA |    ok   1877   2419   542  0      0   33503.5    44293.5 |    ok   1878   2419   541  0      0   33491.8    44574.7 |
         NIA |    ok     17     20     3  0      0     182.3      202.4 |    ok     17     20     3  0      0     182.2      201.2 |
         NRA |    ok   3782   3813    26  0      0    1580.9     4435.0 |    ok   3782   3813    26  0      0    1581.2     4397.7 |
      QF_ABV |    ok  14136  15084   948  0      0   86200.7   556903.7 |    ok  14148  15084   936  0      0   86791.7   545279.6 |
    QF_ABVFP |    ee      0  18093     0  0  18093       1.6      544.4 |    ee      0  18093     0  0  18093       0.0        0.0 |
 QF_ABVFPLRA |    ee      0     74     0  0     74       0.0        0.0 |    ee      0     74     0  0     74       0.0        0.0 |
     QF_ALIA |    ok    119    126     7  0      0    1117.7     5088.6 |    ok    119    126     7  0      0    1116.5     5137.1 |
     QF_ANIA |    ok     74     95    21  0      0    1547.2     5404.6 |    ok     73     95    22  0      0    1553.1     5556.3 |
    QF_AUFBV |    ok     32     56    24  0      0    1459.7    36733.4 |    ok     32     56    24  0      0    1455.0    38069.7 |
   QF_AUFLIA |    ok   1300   1303     3  0      0     934.1     6849.8 |    ok   1300   1303     3  0      0     941.4     6892.6 |
   QF_AUFNIA |    ok      8     17     9  0      0     595.9     1761.7 |    ok      8     17     9  0      0     593.6     1774.6 |
       QF_AX |    ok    549    551     2  0      0     544.6     2691.8 |    ok    549    551     2  0      0     537.4     2798.5 |
       QF_BV |    ok  37010  41713  4695  8      0  360393.8  4558703.8 |    ok  37016  41713  4689  8      0  360042.4  4554366.1 |
     QF_BVFP |    ee      0  17231     0  0  17231       0.0        0.0 |    ee      0  17231     0  0  17231       0.0        0.0 |
  QF_BVFPLRA |    ee      0    168     0  0    168       0.0        0.0 |    ee      0    168     0  0    168       0.0        0.0 |
       QF_DT |    ok   8000   8000     0  0      0      27.7      169.0 |    ok   8000   8000     0  0      0      28.4      174.1 |
       QF_FP |    ee      0  40318     0  0  40318       0.0        0.0 |    ee      0  40318     0  0  40318       0.0        0.0 |
    QF_FPLRA |    ee      0     57     0  0     57       0.0        0.0 |    ee      0     57     0  0     57       0.0        0.0 |
      QF_IDL |    ok   1353   2193   840  0      0   61495.8   415075.5 |    ok   1353   2193   840  0      0   61461.7   411080.9 |
      QF_LIA |    ok   3412   6947  3535  0      0  229786.8  1700601.2 |    ok   3212   6947  3735  0      0  237190.9  2085934.6 |
     QF_LIRA |    ok      5      7     2  0      0     131.0      646.9 |    ok      5      7     2  0      0     131.6      602.6 |
      QF_LRA |    ok   1268   1648   380  0      0   29325.4   151672.1 |    ok   1262   1648   386  0      0   29520.4   150837.6 |
      QF_NIA |    ok   8027  23876  8967  0      0  646709.1  1379487.2 |    ok   8027  23876  8967  0      0  646498.2  1382181.1 |
     QF_NIRA |    ok      1      3     2  0      0     120.2      533.7 |    ok      1      3     2  0      0     120.1      500.3 |
      QF_NRA |    ok   8346  11489  2941  1      0  189604.0   468199.5 |    ok   8344  11489  2943  1      0  189543.1   469185.6 |
      QF_RDL |    ok    185    255    70  0      0    5900.7    23104.7 |    ok    185    255    70  0      0    5891.0    23095.9 |
        QF_S |    ee   1028   2319     0  0   1291       6.5      417.9 |    ee   1028   2319     0  0   1291       6.5      423.9 |
     QF_SLIA |    ee  48075  67584   342  0  19167   25690.2   292796.9 |    ee  48075  67584   342  0  19167   25809.6   297075.2 |
       QF_UF |    ok   7423   7457    34  0      0    5589.4    74994.4 |    ok   7421   7457    36  0      0    5667.3    75309.0 |
     QF_UFBV |    ok   1180   1234    54  0      0    6539.0    97512.4 |    ok   1180   1234    54  0      0    6517.0    96665.0 |
     QF_UFFP |    ee      0      2     0  0      2       0.0        0.0 |    ee      0      2     0  0      2       0.0        0.0 |
    QF_UFIDL |    ok    353    428    75  0      0    6688.3    15677.8 |    ok    351    428    77  0      0    6719.6    15268.7 |
    QF_UFLIA |    ok    579    583     4  0      0     809.0     5804.7 |    ok    579    583     4  0      0     814.9     5847.0 |
    QF_UFLRA |    ok   1267   1284    17  0      0    1294.0    59548.2 |    ok   1267   1284    17  0      0    1291.7    58022.2 |
    QF_UFNIA |    ok    438    478     9  0      0     692.0     3094.8 |    ok    439    478     9  0      0     690.1     2999.9 |
    QF_UFNRA |    ok     13     37    24  0      0    1442.9     3655.7 |    ok     13     37    24  0      0    1443.1     3642.9 |
          UF |    ok   3188   7668  3660  0      0  222044.2   617774.5 |    ok   3187   7668  3660  0      0  222055.7   618603.0 |
        UFBV |    ok     55    121     9  0      0     992.1    23237.0 |    ok     55    121     9  0      0     991.7    23154.8 |
        UFDT |    ok   2096   4527  2002  0      0  121608.3   389108.5 |    ok   2096   4527  2001  0      0  121550.4   389921.3 |
     UFDTLIA |    ok     73    327   243  0      0   14654.0    40226.1 |    ok     73    327   243  0      0   14653.5    40144.5 |
    UFDTLIRA |    ee   8314  10743    26  0    595    1700.7    17672.5 |    ee   8314  10743    26  0    595    1717.4    17885.0 |
     UFDTNIA |    ok      1      1     0  0      0       0.2       25.9 |    ok      1      1     0  0      0       0.3       23.0 |
    UFDTNIRA |    ok   1599   1839    93  0      0    5902.7   191814.4 |    ok   1599   1839    93  0      0    5900.4   193790.5 |
  UFFPDTLIRA |    ee      0    933     0  0    933       1.8      587.9 |    ee      0    933     0  0    933       0.1      149.9 |
  UFFPDTNIRA |    ee      0     21     0  0     21       0.2       63.2 |    ee      0     21     0  0     21       0.0       19.7 |
       UFIDL |    ok     56     68     5  0      0     301.2     1337.0 |    ok     56     68     5  0      0     301.3     1346.2 |
       UFLIA |    ok   7230  10137  2044  0      0  127359.3   555194.2 |    ok   7230  10137  2044  0      0  127403.9   556463.0 |
       UFLRA |    ok     10     15     0  0      0       0.0        0.0 |    ok     10     15     0  0      0       0.0        0.0 |
       UFNIA |    ok   5517  13509  2885  0      0  186233.4  2173402.3 |    ok   5515  13509  2884  0      0  186254.2  2183960.4 |
    __totals |    ee 218554 376601 36981  9 101661 2531548.9 15031201.3 |    ee 218358 376601 37173  9 101661 2539373.7 15413737.1 |```

The only oddball there is `QF_LIA`, where we lose 200 benchmarks, all from the `nec` family.

**Comment by ajreynol** [comment]
For nec with/without --ite-simp (which is an option designed specifically to help this class of benchmarks):
```
                           Configuration  #unsat      time    #sat      time #solved    #total
                         CVC4-120820_def     441   31257.7     444     50811       885      2780
                    CVC4-120820-simp_def     265   21533.3     192   18192.2       457      2780
                    CVC4-120820_ite_simp    1014    105931     843    139384      1857      2780
               CVC4-120820-simp_ite_simp    1009    104602     771    120698      1780      2780





For unsatisfiable : 
                         CVC4-120820_def       X     179       4       4
                    CVC4-120820-simp_def       3       X       0       0
               CVC4-120820-simp_ite_simp     572     744       X       1
                    CVC4-120820_ite_simp     577     749       6       X

For satisfiable : 
                         CVC4-120820_def       X     252      26      24
                    CVC4-120820-simp_def       0       X       8       7
               CVC4-120820-simp_ite_simp     353     587       X       0
                    CVC4-120820_ite_simp     423     658      72       X
```

**Comment by ajreynol** [comment]
I added a new option `--early-ite-removal`, which applies one of the blocks of codes that was removed.  This option is experimental and is only used in combination with `--ite-simp`.  This outperforms the original master on nec:
```
                           Configuration  #unsat      time    #sat      time #solved    #total
                         CVC4-120820_def     441   31257.7     444     50811       885      2780
                    CVC4-120820-simp_def     265   21533.3     192   18192.2       457      2780
                    CVC4-120820_ite_simp    1014    105931     843    139384      1857      2780
               CVC4-120820-simp_ite_simp    1009    104602     771    120698      1780      2780
                     CVC4-121020-sid_eir     440   31003.2     446   51338.2       886      2780
            CVC4-121020-sid_ite_simp_eir    1015    105948     851    141221      1866      2780

For unsatisfiable : 
                         CVC4-120820_def       X     179       4       4       1       4
                    CVC4-120820-simp_def       3       X       0       0       3       0
               CVC4-120820-simp_ite_simp     572     744       X       1     573       0
                    CVC4-120820_ite_simp     577     749       6       X     578       1
                     CVC4-121020-sid_eir       0     178       4       4       X       4
            CVC4-121020-sid_ite_simp_eir     578     750       6       2     579       X

For satisfiable : 
                         CVC4-120820_def       X     252      26      24       0      25
                    CVC4-120820-simp_def       0       X       8       7       0       8
               CVC4-120820-simp_ite_simp     353     587       X       0     351       1
                    CVC4-120820_ite_simp     423     658      72       X     421       6
                     CVC4-121020-sid_eir       2     254      26      24       X      25
            CVC4-121020-sid_ite_simp_eir     432     667      81      14     430       X
```
(eir = early ITE removal).  

This means that after this PR, we slightly gain performance on nec regardless of whether --ite-simp is used, and have little to no change on all other logics in SMT-LIB.

Thus, this PR is ready to review / merge.

**Review by HanielB — APPROVED** [review]
LGTM, given the evaluation.

**Comment by ajreynol** [comment]
I think we were going to wait to get results for `--decision=justification` on SMT-LIB, and perhaps --decision=justification + incremental SMT-LIB.

**Comment by HanielB** [comment]
Running on the barrett cluster with 60s timeout on all non-incremental SMT-LIB, with `--decision=justification`, and the updated version of this branch:
```
   DIRECTORY |                                              master-just |                                              branch-just |
   Benchmark |  Stat   Slvd    Tot    To Mo    Err    Cpu[s]    Mem[MB] |  Stat   Slvd    Tot    To Mo    Err    Cpu[s]    Mem[MB] |
         ABV |    ok     17    169     0  0      0       1.5      200.0 |    ok     17    169     0  0      0       1.3      186.6 |
       ABVFP |    ee      0     30     0  0     30       0.0        0.0 |    ee      0     30     0  0     30       0.0        0.0 |
    ABVFPLRA |    ee      0     75     0  0     75       0.0        0.0 |    ee      0     75     0  0     75       0.0        0.0 |
        ALIA |    ok     35     42     0  0      0       1.9      122.1 |    ok     35     42     0  0      0       1.4      100.6 |
  AUFBVDTLIA |    ok    412   1708   865  0      0   52077.5   374622.2 |    ok    411   1708   855  0      0   51456.6   332873.8 |
  AUFBVDTNIA |    ok      0      1     0  0      0       0.0        0.0 |    ok      0      1     0  0      0       0.0        0.0 |
    AUFDTLIA |    ok    635    728     0  0      0       0.1       18.9 |    ok    635    728     0  0      0       0.0        0.0 |
   AUFDTLIRA |    ee  10317  12196   122  0    519    7659.1    52012.9 |    ee  10317  12196   122  0    519    7653.1    55100.8 |
   AUFDTNIRA |    ok    325    471    74  0      0    4525.4    90781.5 |    ok    325    471    73  0      0    4430.5    85940.8 |
 AUFFPDTLIRA |    ee      0    154     0  0    154       0.0        0.0 |    ee      0    154     0  0    154       0.0        0.0 |
 AUFFPDTNIRA |    ee      0     13     0  0     13       0.0        0.0 |    ee      0     13     0  0     13       0.0        0.0 |
      AUFLIA |    ok   2027   3276   430  0      0   26990.4   206624.8 |    ok   2027   3276   430  0      0   26977.2   207527.7 |
     AUFLIRA |    ok  19734  20011   117  0      0    7918.2    31277.5 |    ok  19733  20011   118  0      0    7907.9    31525.5 |
      AUFNIA |    ok      0      3     0  0      0       0.0        0.0 |    ok      0      3     0  0      0       0.0        0.0 |
     AUFNIRA |    ok   1033   1480   400  0      0   24321.3    88224.2 |    ok   1033   1480   400  0      0   24319.2    88414.1 |
          BV |    ok   5447   5846   399  0      0   25502.2   246848.6 |    ok   5452   5846   394  0      0   25329.3   248455.0 |
        BVFP |    ee      0    224     0  0    224       0.0        0.0 |    ee      0    224     0  0    224       0.0        0.0 |
     BVFPLRA |    ee      0    185     0  0    185       0.0        0.0 |    ee      0    185     0  0    185       0.0        0.0 |
          FP |    ee      0   2484     0  0   2484       0.0        0.0 |    ee      0   2484     0  0   2484       0.0        0.0 |
       FPLRA |    ee      0     27     0  0     27       0.0        0.0 |    ee      0     27     0  0     27       0.0        0.0 |
         LIA |    ok    576    607    31  0      0    1918.2     5014.7 |    ok    576    607    31  0      0    1914.8     5448.5 |
         LRA |    ok   1878   2419   541  0      0   33510.2    44311.8 |    ok   1878   2419   541  0      0   33496.2    44874.0 |
         NIA |    ok     17     20     3  0      0     182.2      201.9 |    ok     17     20     3  0      0     182.3      205.7 |
         NRA |    ok   3782   3813    26  0      0    1582.1     4380.6 |    ok   3782   3813    26  0      0    1581.5     4436.4 |
      QF_ABV |    ok  14139  15084   945  0      0   86321.7   554239.0 |    ok  14149  15084   935  0      0   86537.0   546557.8 |
    QF_ABVFP |    ee      0  18093     0  0  18093       0.0        5.2 |    ee      0  18093     0  0  18093       0.0        0.0 |
 QF_ABVFPLRA |    ee      0     74     0  0     74       0.0        0.0 |    ee      0     74     0  0     74       0.0        0.0 |
     QF_ALIA |    ok    120    126     6  0      0     800.2     2102.8 |    ok    120    126     6  0      0     791.3     2206.3 |
     QF_ANIA |    ok     84     95    11  0      0     886.4     2667.8 |    ok     84     95    11  0      0     880.9     2683.1 |
    QF_AUFBV |    ok     32     56    24  0      0    1460.1    37714.8 |    ok     32     56    24  0      0    1455.1    37569.7 |
   QF_AUFLIA |    ok   1300   1303     3  0      0     787.8     7016.9 |    ok   1300   1303     3  0      0     777.3     7065.9 |
   QF_AUFNIA |    ok     17     17     0  0      0      93.1      715.8 |    ok     17     17     0  0      0      91.0      734.1 |
       QF_AX |    ok    551    551     0  0      0     307.3     2660.7 |    ok    551    551     0  0      0     305.1     2815.3 |
       QF_BV |    ok  37010  41713  4695  8      0  360635.4  4564625.2 |    ok  37011  41713  4694  8      0  359683.6  4575774.5 |
     QF_BVFP |    ee      0  17231     0  0  17231       0.0        0.0 |    ee      0  17231     0  0  17231       0.0        0.0 |
  QF_BVFPLRA |    ee      0    168     0  0    168       0.0        0.0 |    ee      0    168     0  0    168       0.0        0.0 |
       QF_DT |    ok   8000   8000     0  0      0      29.5      173.6 |    ok   8000   8000     0  0      0      28.5      173.6 |
       QF_FP |    ee      0  40318     0  0  40318       0.0        0.0 |    ee      0  40318     0  0  40318       0.0        0.0 |
    QF_FPLRA |    ee      0     57     0  0     57       0.0        0.0 |    ee      0     57     0  0     57       0.0        0.0 |
      QF_IDL |    ok   1132   2193  1061  0      0   71460.9   400213.0 |    ok   1132   2193  1061  0      0   71379.3   399012.6 |
      QF_LIA |    ok   3375   6947  3566  6      0  235428.6  2827226.0 |    ok   3780   6947  3159  8      0  221305.3  3365133.5 |
     QF_LIRA |    ok      3      7     4  0      0     241.7     1714.1 |    ok      3      7     4  0      0     241.6     1689.5 |
      QF_LRA |    ok   1206   1648   442  0      0   31744.2   143195.7 |    ok   1198   1648   450  0      0   31890.2   142939.7 |
      QF_NIA |    ok   7781  23876  6551  0      0  478696.6  1468689.4 |    ok   7782  23876  6544  0      0  478415.4  1481376.7 |
     QF_NIRA |    ok      1      3     2  0      0     120.1      628.2 |    ok      1      3     2  0      0     120.2      585.4 |
      QF_NRA |    ok   8507  11489  2793  0      0  178827.8   503282.4 |    ok   8507  11489  2793  0      0  178839.7   505989.6 |
      QF_RDL |    ok    138    255   117  0      0    7842.1    22314.4 |    ok    138    255   117  0      0    7831.5    22428.5 |
        QF_S |    ee   1028   2319     0  0   1291       6.3      438.2 |    ee   1028   2319     0  0   1291       6.9      997.3 |
     QF_SLIA |    ee  48075  67584   342  0  19167   25889.6   291624.8 |    ee  48075  67584   342  0  19167   25761.5   340815.3 |
       QF_UF |    ok   7352   7457   105  0      0   13055.8    89008.8 |    ok   7355   7457   102  0      0   12884.9    89890.9 |
     QF_UFBV |    ok   1180   1234    54  0      0    6603.4    97829.6 |    ok   1179   1234    55  0      0    6566.3    97192.3 |
     QF_UFFP |    ee      0      2     0  0      2       0.0        0.0 |    ee      0      2     0  0      2       0.0        0.0 |
    QF_UFIDL |    ok    282    428   146  0      0    9741.9    18582.0 |    ok    283    428   145  0      0    9732.1    18402.7 |
    QF_UFLIA |    ok    509    583    74  0      0    5012.4     7311.0 |    ok    510    583    73  0      0    4996.2     7348.6 |
    QF_UFLRA |    ok   1270   1284    14  0      0    1347.5    58934.8 |    ok   1271   1284    13  0      0    1336.8    60392.9 |
    QF_UFNIA |    ok    444    478     1  0      0     139.5     1275.0 |    ok    443    478     1  0      0     130.4     1503.5 |
    QF_UFNRA |    ok     14     37    23  0      0    1439.7     3671.4 |    ok     14     37    23  0      0    1442.1     3690.5 |
          UF |    ok   3187   7668  3661  0      0  222064.2   618148.4 |    ok   3187   7668  3661  0      0  222065.4   620248.4 |
        UFBV |    ok     55    121     9  0      0     990.9    23083.9 |    ok     55    121     9  0      0     991.9    23227.5 |
        UFDT |    ok   2096   4527  2002  0      0  121616.9   389027.6 |    ok   2097   4527  2001  0      0  121614.6   398188.7 |
     UFDTLIA |    ok     73    327   243  0      0   14653.9    39924.1 |    ok     73    327   243  0      0   14651.9    40396.4 |
    UFDTLIRA |    ee   8314  10743    26  0    595    1718.8    18123.4 |    ee   8314  10743    26  0    595    1716.8    18193.9 |
     UFDTNIA |    ok      1      1     0  0      0       0.2       26.0 |    ok      1      1     0  0      0       0.2       26.8 |
    UFDTNIRA |    ok   1599   1839    93  0      0    5909.9   180556.4 |    ok   1598   1839    92  0      0    5727.6   168147.9 |
  UFFPDTLIRA |    ee      0    933     0  0    933       0.0        0.0 |    ee      0    933     0  0    933       0.0       81.5 |
  UFFPDTNIRA |    ee      0     21     0  0     21       0.0        9.8 |    ee      0     21     0  0     21       0.0       19.8 |
       UFIDL |    ok     56     68     5  0      0     301.4     1338.4 |    ok     56     68     5  0      0     301.3     1347.0 |
       UFLIA |    ok   7230  10137  2044  0      0  127450.0   556013.2 |    ok   7229  10137  2045  0      0  127510.5   558933.1 |
       UFLRA |    ok     10     15     0  0      0       0.0        0.0 |    ok     10     15     0  0      0       0.0        0.0 |
       UFNIA |    ok   5516  13509  2884  0      0  186346.6  2164273.7 |    ok   5513  13509  2889  0      0  186560.7  2211416.2 |
    __totals |    ee 217922 376601 34954 14 101661 2386162.9 16243027.2 |    ee 218334 376601 34521 16 101661 2369822.4 16860286.5 |
```
Note that again the discrepancy is QF_LIA, but with the branch solving over 400 more benchmarks, all but two on the `nec` family.

**Comment by ajreynol** [comment]
Analysis on nec from Starexec, 300 sec timeout:
```
                           Configuration  #unsat      time    #sat      time #solved    #total
                         CVC4-120820_def     441   31257.7     444     50811       885      2780
                    CVC4-120820-simp_def     265   21533.3     192   18192.2       457      2780
                    CVC4-120820_ite_simp    1014    105931     843    139384      1857      2780
               CVC4-120820-simp_ite_simp    1009    104602     771    120698      1780      2780
                     CVC4-121020-sid_eir     440   31003.2     446   51338.2       886      2780
            CVC4-121020-sid_ite_simp_eir    1015    105948     851    141221      1866      2780
                      CVC4-121020-sid_dj     965   96844.7     841   79989.4      1806      2780

For unsatisfiable : 
                         CVC4-120820_def       X     179       4       4       1       4      14
                    CVC4-120820-simp_def       3       X       0       0       3       0       5
               CVC4-120820-simp_ite_simp     572     744       X       1     573       0     320
                    CVC4-120820_ite_simp     577     749       6       X     578       1     324
                     CVC4-121020-sid_eir       0     178       4       4       X       4      14
            CVC4-121020-sid_ite_simp_eir     578     750       6       2     579       X     325
                      CVC4-121020-sid_dj     538     705     276     275     539     275       X

For satisfiable : 
                         CVC4-120820_def       X     252      26      24       0      25      22
                    CVC4-120820-simp_def       0       X       8       7       0       8       0
               CVC4-120820-simp_ite_simp     353     587       X       0     351       1     100
                    CVC4-120820_ite_simp     423     658      72       X     421       6     140
                     CVC4-121020-sid_eir       2     254      26      24       X      25      22
            CVC4-121020-sid_ite_simp_eir     432     667      81      14     430       X     146
                      CVC4-121020-sid_dj     419     649     170     138     417     136       X
```

dj = `--decision-justification`, eir = `--early-ite-removal`, ite_simp = `--ite-simp`.

Summary, disabling all ITE preprocessing and just running `--decision=justification` is *almost* as good as enabling `--ite-simp --early-ite-removal`.

I believe this will improve further once ITE removal is delayed until after CNF.

**Comment by ajreynol** [comment]
I believe this PR is ready to go, as we have no performance degradation (with or without --decision=justification).

@barrettcw  what do you think?

**Review by 4tXJ7f — APPROVED** [review]
Nice results :)

**Pull request merged**
