### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by FabianWolff**
While working on the Debian package for CVC4, our linter found several spelling errors in the code. This pull request fixes them.

### CODE REVIEW

**Review by nafur — APPROVED** [review]
LGTM. Thanks for the improvements!

**Comment by 4tXJ7f** [comment]
@FabianWolff Thanks a lot for the PRs. Could you please sign your commits as described [here](https://github.com/CVC4/CVC4/blob/52bab1414d41a4beb301f3c8a4165fa972f71a93/CONTRIBUTING.md)?

**Comment by FabianWolff** [comment]
> @FabianWolff Thanks a lot for the PRs. Could you please sign your commits as described [here](https://github.com/CVC4/CVC4/blob/52bab1414d41a4beb301f3c8a4165fa972f71a93/CONTRIBUTING.md)?

Sorry about that, I did not check the contributing guidelines because it's usually no big deal for small patches like this, but I signed my commit now.

**Comment by 4tXJ7f** [comment]
> Sorry about that, I did not check the contributing guidelines because it's usually no big deal for small patches like this, but I signed my commit now.

Thanks! Yeah, since we are not lawyers, we just tend to err on the side of caution. I wish that these things were easier :/

**Pull request merged**
