### PR TITLE
Refactor sygus stats

### PR DESCRIPTION
**Pull request by ajreynol**
This makes the sygus statistics class standalone.  This will make it possible to define further statistics without accessing data in the SynthEngine.

### CODE REVIEW

**Comment by HanielB** [comment]
I don't quite understand the motivation. Could you elaborate?

**Comment by ajreynol** [comment]
I would like to add more statistics for sygus, however its statistics class lives within SynthEngine.  Instead, I would like to have the SygusStatistics class be standalone and pass it to all the submodules.  In theory this could be done currently, but I'd have to pass around a statistics object that is defined within SynthEngine, which looks really ugly.

**Comment by HanielB** [comment]
Doesn't everybody have access to SynthEngine already? Passing a statistics module everywhere does not seem very clean to me... this is the kind of information I'd expect to be centralized in the driver of the component.

**Comment by ajreynol** [comment]
It does live there, we are passing a reference.  Otherwise everything has to have access to the *SynthEngine* itself.  You can already see an example of this in SynthConjecture.

**Pull request merged**
