### PR TITLE
Ignore isInConflict when adding conflicts

### PR DESCRIPTION
**Pull request by nafur**
Right now, the inference manager infrastructure drops conflicts (and literal propagations) if the solver already is in a conflict.
This PR removes this behavior. The current setup in linear arithmetic requires adding conflicts, even when already in conflict, and experiments showed a small but beneficial effect of this change.

### CODE REVIEW

**Comment by nafur** [comment]
Experimental results (only diffs shown, comparing master to this PR + linear arithmetic using the inference manager infrastructure, added in another PR in the near future).
non-incremental:
```
                                   status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark  config                                                                                                                 
AUFDTLIRA  02230541-linear-noninc/     ok      1       1    0      1     1        0       0      0     1       0     266.0    57.9
           02230541-master-noninc/     to      1       0    0      0     0        1       0      0     0       0     600.0   116.7
FP         02230541-linear-noninc/     ok      2       1    0      1     1        1       0      0     1       0    1200.1  7352.5
           02230541-master-noninc/     ok      2       1    0      1     1        1       0      0     1       0    1182.8  7545.3
QF_ABV     02230541-linear-noninc/     ok    110      95   91      4    95       15       0      0    95       0   43574.3 28131.6
           02230541-master-noninc/     ok    110      15   14      1    15       95       0      0    15       0   63808.9 29888.3
QF_ALIA    02230541-linear-noninc/     ok      1       1    0      1     1        0       0      0     1       0     554.9   143.9
           02230541-master-noninc/     to      1       0    0      0     0        1       0      0     0       0     600.0   139.1
QF_AUFNIA  02230541-linear-noninc/     ok      3       1    1      0     1        2       0      0     1       0    1664.3   929.8
           02230541-master-noninc/     ok      3       2    1      1     2        1       0      0     2       0    1104.1   606.3
QF_BV      02230541-linear-noninc/     ok     18      12    8      4    12        6       0      0    12       0    9071.7 20405.2
           02230541-master-noninc/     ok     18       6    3      3     6       12       0      0     6       0    9471.3 22278.7
QF_BVFP    02230541-linear-noninc/     ok      1       1    0      1     1        0       0      0     1       0     583.7  2304.1
           02230541-master-noninc/     to      1       0    0      0     0        1       0      0     0       0     600.1  2202.0
QF_BVFPLRA 02230541-linear-noninc/     ok      2       2    0      2     2        0       0      0     2       0    1077.5  2666.0
           02230541-master-noninc/     to      2       0    0      0     0        2       0      0     0       0    1200.2  2103.9
QF_IDL     02230541-linear-noninc/     ok      6       5    3      2     5        1       0      0     5       0    3455.4  1320.8
           02230541-master-noninc/     ok      6       1    1      0     1        5       0      0     1       0    3587.1  1301.6
QF_LIA     02230541-linear-noninc/     ok      3       2    1      1     2        1       0      0     2       0    1781.7   860.3
           02230541-master-noninc/     ok      3       1    1      0     1        2       0      0     1       0    1798.1   861.1
QF_LRA     02230541-linear-noninc/     ok      2       1    1      0     1        1       0      0     1       0    1189.8   476.3
           02230541-master-noninc/     ok      2       1    0      1     1        1       0      0     1       0    1194.7   464.6
QF_NIA     02230541-linear-noninc/     ok      8       8    1      7     8        0       0      0     8       0    4710.2  1287.9
           02230541-master-noninc/     to      8       0    0      0     0        8       0      0     0       0    4800.2  1268.5
QF_NRA     02230541-linear-noninc/     ok     14       9    8      1     9        5       0      0     9       0    4278.3  2059.0
           02230541-master-noninc/     ok     14       5    4      1     5        9       0      0     5       0    5594.3  1718.9
QF_UFIDL   02230541-linear-noninc/     to      2       0    0      0     0        2       0      0     0       0    1200.0   159.7
           02230541-master-noninc/     ok      2       2    0      2     2        0       0      0     2       0     982.5   153.6
QF_UFNIA   02230541-linear-noninc/     ok      7       6    6      0     6        1       0      0     6       0     617.3   471.3
           02230541-master-noninc/     ok      7       1    1      0     1        2       0      0     1       0    1226.5   468.6
QF_UFNRA   02230541-linear-noninc/     to      1       0    0      0     0        1       0      0     0       0     600.1    15.2
           02230541-master-noninc/     ok      1       1    1      0     1        0       0      0     1       0     297.7    14.3
UFDTNIRA   02230541-linear-noninc/     ok      2       2    0      2     2        0       0      0     2       0      62.5  2266.3
           02230541-master-noninc/     to      2       0    0      0     0        2       0      0     0       0    1200.0    43.0
UFLIA      02230541-linear-noninc/     ok      1       1    0      1     1        0       0      0     1       0     553.5   137.9
           02230541-master-noninc/     to      1       0    0      0     0        1       0      0     0       0     600.0   120.5
UFNIA      02230541-linear-noninc/     ok    161     160   10    150   160        1       0      0   160       0   11859.9 27361.1
           02230541-master-noninc/     ok    161       1    0      1     1      158       0      0     1       0   96184.8  9304.6
```
incremental:
```
                                 status  total   solved      sat   unsat  best  timeout  memout  error  uniq  disagr  time_cpu    memory
benchmark   config                                                                                                                      
ABVFP       02230541-linear-inc/     ok      4      818      801      17     3        1       0      0     0       0     611.8     436.6
            02230541-master-inc/     ok      4      818      801      17     2        1       0      0     0       0     612.1     437.5
ALIA        02230541-linear-inc/     ok     24   202552   193238    9314    21        0       0      0     0       0     704.6    2536.8
            02230541-master-inc/     ok     24   189307   181077    8230     4       16       0      0     0       0    9733.7    2750.2
ANIA        02230541-linear-inc/     ok      3    23488    22768     720     3        0       0      0     0       0      78.4     166.7
            02230541-master-inc/     to      3      537      507      30     0        3       0      0     0       0    1800.1     168.3
AUFNIRA     02230541-linear-inc/     ok    139     3108        0    3108   119        0       0      0     0       0     269.4    1798.1
            02230541-master-inc/     ok    139     3108        0    3108   112        0       0      0     0       0     241.0    1812.5
BV          02230541-linear-inc/     ok     18    35909    32524    3385    13        7       0      0     0       0    5038.6   17225.8
            02230541-master-inc/     ok     18    35908    32523    3385    11        7       0      0     0       0    5048.2   17182.1
BVFP        02230541-linear-inc/     ok     10     3422     3062     360     7        6       0      0     0       0    3652.7    1659.4
            02230541-master-inc/     ok     10     3422     3062     360     9        6       0      0     0       0    3651.7    1661.7
LIA         02230541-linear-inc/     ok      6    25393    21716    3677     4        0       0      0     0       0      26.4     144.8
            02230541-master-inc/     ok      6    25393    21716    3677     5        0       0      0     0       0      26.4     145.0
LRA         02230541-linear-inc/     ok      5    15969    15901      68     5        0       0      0     0       0      79.6     520.0
            02230541-master-inc/     ok      5    15969    15901      68     1        0       0      0     0       0      81.8     521.1
QF_ABV      02230541-linear-inc/     ok    953     2321      964    1357   752       22       0      0     0       0   27728.4   98540.3
            02230541-master-inc/     ok    953     2321      964    1357   623       22       0      0     0       0   27787.2   98517.1
QF_ABVFP    02230541-linear-inc/     ok     14     1960     1868      92    11        1       0      0     0       0     932.8    5450.3
            02230541-master-inc/     ok     14     1960     1868      92    10        1       0      0     0       0     927.9    5450.3
QF_ALIA     02230541-linear-inc/     ok     44   530398   496955   33443    40        0       0      0     0       0    2934.6    9943.0
            02230541-master-inc/     ok     44   494498   466275   28223     6        9       0      0     0       0    8373.5   10751.9
QF_ANIA     02230541-linear-inc/     ok      5    43429    41973    1456     3        1       0      0     0       0     832.3    1587.9
            02230541-master-inc/     ok      5    43429    41973    1456     3        1       0      0     0       0     843.2    1583.4
QF_AUFBV    02230541-linear-inc/     ok     30      624        7     617    15       17       0      0     0       0   10562.1   13824.3
            02230541-master-inc/     ok     30      624        7     617    24       17       0      0     0       0   10551.1   13858.2
QF_AUFBVLIA 02230541-linear-inc/     ok    343      685      346     339   234        1       0      0     0       0   20154.1  101444.4
            02230541-master-inc/     ok    343      685      346     339   194        1       0      0     0       0   20069.4  100139.4
QF_AUFBVNIA 02230541-linear-inc/     ok     21       42       21      21    15        0       0      0     0       0     820.6    5505.5
            02230541-master-inc/     ok     21       42       21      21     9        0       0      0     0       0     866.6    5500.2
QF_AUFLIA   02230541-linear-inc/     ok     72  3422333  2838330  584003    53       15       0      0     0       0   10256.7   23027.1
            02230541-master-inc/     ok     72  3432352  2849113  583239    56       15       0      0     0       0   10256.3   22599.8
QF_BV       02230541-linear-inc/     ok   1205    49885    43920    5965   985       36       3      0     0       0   27357.9  108869.1
            02230541-master-inc/     ok   1205    49887    43924    5963   907       36       3      0     1       0   27534.8  109126.3
QF_BVFP     02230541-linear-inc/     ok    114    32839    32167     672    88        0       0      0     0       0     530.4    9155.5
            02230541-master-inc/     ok    114    32839    32167     672    92        0       0      0     0       0     528.4    9162.9
QF_FP       02230541-linear-inc/     ok      2       52       41      11     2        0       0      0     0       0       0.5      19.5
            02230541-master-inc/     ok      2       52       41      11     1        0       0      0     0       0       0.6      17.6
QF_LIA      02230541-linear-inc/     ok     69  3768024  2932481  835543    43       52       0      0     0       0   32939.8   44891.8
            02230541-master-inc/     ok     69  3757119  2921757  835362    39       52       0      0     0       0   32976.8   45668.3
QF_LRA      02230541-linear-inc/     to     10      535      123     412     3       10       0      0     0       0    6008.1    9520.8
            02230541-master-inc/     to     10      537      124     413     9       10       0      0     0       0    6007.1    9768.5
QF_NIA      02230541-linear-inc/     ok     10  1856608  1809501   47107     8        9       0      0     0       0    5775.7    4922.1
            02230541-master-inc/     ok     10  1849353  1802351   47002     5        9       0      0     0       0    5798.5    4735.0
QF_UF       02230541-linear-inc/     ok    766     1532     1070     462   584        0       0      0     0       0    1021.7   40148.1
            02230541-master-inc/     ok    766     1532     1070     462   597        0       0      0     0       0    1017.9   40181.3
QF_UFBV     02230541-linear-inc/     ok   2323     5186     3332    1854  1484        8       2      0     0       0   22644.9  173073.7
            02230541-master-inc/     ok   2323     5186     3332    1854  1614        8       2      0     0       0   22498.2  173115.6
QF_UFBVLIA  02230541-linear-inc/     ok     28       56       45      11    27        0       0      0     0       0       5.4     327.6
            02230541-master-inc/     ok     28       56       45      11    25        0       0      0     0       0       5.6     331.1
QF_UFFP     02230541-linear-inc/     ok      1        2        0       2     0        0       0      0     0       0       0.6      59.5
            02230541-master-inc/     ok      1        2        0       2     1        0       0      0     0       0       0.5      32.4
QF_UFLIA    02230541-linear-inc/     ok    603   562003   534479   27524   408      204       0      0     0       0  124994.5   31838.3
            02230541-master-inc/     ok    603   564240   536475   27765   520      203       0      0     0       0  125201.8   32171.7
QF_UFLRA    02230541-linear-inc/     ok   3047    20534    12842    7692  2435       53       1      0     0       0   74465.6  298405.4
            02230541-master-inc/     ok   3047    20534    12840    7694  2392       51       1      0     0       0   75039.9  298749.7
QF_UFNIA    02230541-linear-inc/     ok      1    84573    78989    5584     0        0       0      0     0       0     423.5     191.4
            02230541-master-inc/     ok      1    84573    78989    5584     1        0       0      0     0       0     402.5     191.5
UF          02230541-linear-inc/     ok   2980    80040    32924   47116  2432      360     129      0     0       0  282074.4 1233822.8
            02230541-master-inc/     ok   2980    80040    32924   47116  2319      360     129      0     0       0  282263.9 1233795.5
UFLRA       02230541-linear-inc/     ok   1038   240622        0  240622   737       30       0      0     0       0   48029.6   14801.8
            02230541-master-inc/     ok   1038   240500        0  240500   510       32       0      0     0       0   48801.0   14825.7
UFNIA       02230541-linear-inc/     ok   3172    98625    28806   69819  2555      445     125      0     0       0  351932.2 1299106.6
            02230541-master-inc/     ok   3172    96377    28580   67797  2370      477     125      0     0       0  366866.7 1297260.8
UFNRA       02230541-linear-inc/     ok      3       10        6       4     3        0       0      0     0       0       0.5       9.5
            02230541-master-inc/     ok      3       10        6       4     3        0       0      0     0       0       0.5       9.9
```

**Comment by ajreynol** [comment]
This is great, +160-1 on UFNIA +95-15 on QF_ABV I would not classify as a "small" improvement :-)

**Review by ajreynol — APPROVED** [review]
LGTM.

FYI, I'm a bit curious which one of these changes led to the improvement.  E.g. I'm wondering if say, the check for conflict still ok on propagateLit but not the others.  I would be the most surprised if that one was leading to worse performance.

**Comment by nafur** [comment]
So we decided to do benchmarks for this particular PR without the changes for linear arithmetic. We compare `master`, `pr-both` (this PR) and `pr-confl` (this PR without the changes to `propagateLit`).

Diffs on non-incremental:
```
                         status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
config                                                                                                                  
03020833-pr-confl-noninc     ok     87      49   21     28    23       38       0      0    11       0   23288.4 43196.7
03020833-pr-both-noninc/     ok     87      45   26     19    34       42       0      0     5       0   23316.0 43128.5
03020819-master-noninc/      ok     87      41   19     22    30       47       0      0    23       0   23931.0 43098.4

                                    status  total  solved  sat  unsat  best  timeout  memout  error  uniq  disagr  time_cpu  memory
benchmark  config                                                                                                                  
AUFNIRA    03020819-master-noninc/      to      1       0    0      0     0        1       0      0     0       0     300.3   193.2
           03020833-pr-both-noninc/     ok      1       1    0      1     1        0       0      0     1       0     298.0   207.7
           03020833-pr-confl-noninc     to      1       0    0      0     0        1       0      0     0       0     300.3   209.3
QF_ABV     03020819-master-noninc/      ok     29      12    7      5    12       17       0      0    12       0    7403.0  5395.8
           03020833-pr-both-noninc/     ok     29      17   13      4    13       12       0      0     0       0    6882.2  5231.8
           03020833-pr-confl-noninc     ok     29      17   13      4     4       12       0      0     0       0    6898.8  5234.1
QF_BV      03020819-master-noninc/      ok     28      13    8      5     8       15       0      0     7       0    7555.8 20346.6
           03020833-pr-both-noninc/     ok     28      13    9      4    12       15       0      0     2       0    7503.3 20532.5
           03020833-pr-confl-noninc     ok     28      16    7      9     8       12       0      0     5       0    7580.6 20524.9
QF_BVFP    03020819-master-noninc/      to      1       0    0      0     0        1       0      0     0       0     300.3  1141.1
           03020833-pr-both-noninc/     to      1       0    0      0     0        1       0      0     0       0     300.3  1147.8
           03020833-pr-confl-noninc     ok      1       1    0      1     1        0       0      0     1       0     287.4  1161.5
QF_BVFPLRA 03020819-master-noninc/      to      1       0    0      0     0        1       0      0     0       0     300.3   912.0
           03020833-pr-both-noninc/     to      1       0    0      0     0        1       0      0     0       0     300.3   913.4
           03020833-pr-confl-noninc     ok      1       1    0      1     1        0       0      0     1       0     218.3   956.8
QF_FP      03020819-master-noninc/      to      1       0    0      0     0        1       0      0     0       0     300.3  2008.2
           03020833-pr-both-noninc/     to      1       0    0      0     0        1       0      0     0       0     300.3  1988.4
           03020833-pr-confl-noninc     ok      1       1    0      1     1        0       0      0     1       0     299.2  2008.5
QF_IDL     03020819-master-noninc/      to      3       0    0      0     0        3       0      0     0       0     901.0  1131.1
           03020833-pr-both-noninc/     ok      3       3    0      3     3        0       0      0     1       0     893.9  1143.5
           03020833-pr-confl-noninc     ok      3       2    0      2     0        1       0      0     0       0     896.2  1112.9
QF_LIA     03020819-master-noninc/      ok      4       4    2      2     4        0       0      0     2       0    1194.4  1016.0
           03020833-pr-both-noninc/     ok      4       1    0      1     0        3       0      0     0       0    1201.2  1014.4
           03020833-pr-confl-noninc     ok      4       1    0      1     0        3       0      0     0       0    1200.1  1015.4
QF_LRA     03020819-master-noninc/      ok      3       2    0      2     1        1       0      0     0       0     895.6   429.1
           03020833-pr-both-noninc/     ok      3       1    1      0     1        2       0      0     0       0     895.7   438.8
           03020833-pr-confl-noninc     ok      3       3    1      2     1        0       0      0     0       0     894.6   440.3
QF_NIA     03020819-master-noninc/      ok     10       7    1      6     4        4       0      0     2       0    2989.6  1338.8
           03020833-pr-both-noninc/     ok     10       5    2      3     3        5       0      0     1       0    2992.1  1327.4
           03020833-pr-confl-noninc     ok     10       3    0      3     3        7       0      0     2       0    2992.8  1335.6
QF_UFBV    03020819-master-noninc/      ok      1       1    1      0     0        0       0      0     0       0     293.6   179.5
           03020833-pr-both-noninc/     ok      1       1    1      0     1        0       0      0     0       0     270.4   175.9
           03020833-pr-confl-noninc     to      1       0    0      0     0        1       0      0     0       0     300.3   175.0
UFLIA      03020819-master-noninc/      ok      1       1    0      1     0        0       0      0     0       0     299.4   120.7
           03020833-pr-both-noninc/     to      1       0    0      0     0        1       0      0     0       0     300.3   119.7
           03020833-pr-confl-noninc     ok      1       1    0      1     1        0       0      0     0       0     291.5   117.9
UFNIA      03020819-master-noninc/      ok      4       1    0      1     1        3       0      0     0       0    1197.4  8886.3
           03020833-pr-both-noninc/     ok      4       3    0      3     0        1       0      0     0       0    1178.0  8887.2
           03020833-pr-confl-noninc     ok      4       3    0      3     3        1       0      0     1       0    1128.3  8904.5
```

Diffs on incremental:
```
                       status  total   solved      sat    unsat   best  timeout  memout  error  uniq  disagr  time_cpu    memory
config                                                                                                                          
03020819-master-inc/       ok  17036  7960018  6387855  1572163  12087     1667      18      0     0       0  637891.2 3201648.9
03020833-pr-both-inc/      ok  17036  7944596  6373504  1571092  12184     1668      19      0     0       0  637703.5 3196868.0
03020833-pr-confl-inc/     ok  17036  7866547  6301090  1565457  11498     1666      18      0     0       0  638137.8 3201266.7

                                   status  total   solved      sat   unsat  best  timeout  memout  error  uniq  disagr  time_cpu    memory
benchmark   config                                                                                                                        
ABVFP       03020819-master-inc/       ok      4      818      801      17     2        1       0      0     0       0     311.4     410.2
            03020833-pr-both-inc/      ok      4      818      801      17     4        1       0      0     0       0     311.2     410.8
            03020833-pr-confl-inc/     ok      4      818      801      17     3        1       0      0     0       0     311.4     412.5
ALIA        03020819-master-inc/       ok     24   189307   181077    8230    15       16       0      0     0       0    4926.2    2686.3
            03020833-pr-both-inc/      ok     24   189307   181077    8230    19       16       0      0     0       0    4925.3    2683.1
            03020833-pr-confl-inc/     ok     24   189307   181077    8230    20       16       0      0     0       0    4926.1    2665.6
ANIA        03020819-master-inc/       to      3      509      479      30     3        3       0      0     0       0     900.9     151.4
            03020833-pr-both-inc/      to      3      509      479      30     3        3       0      0     0       0     900.9     147.3
            03020833-pr-confl-inc/     to      3      509      479      30     3        3       0      0     0       0     900.9     148.6
AUFNIRA     03020819-master-inc/       ok    139     3108        0    3108   103        0       0      0     0       0     220.2    1669.4
            03020833-pr-both-inc/      ok    139     3108        0    3108   110        0       0      0     0       0     218.6    1665.5
            03020833-pr-confl-inc/     ok    139     3108        0    3108   102        0       0      0     0       0     220.4    1668.2
BV          03020819-master-inc/       ok     18    35859    32488    3371     9        7       0      0     0       0    2943.3    7943.9
            03020833-pr-both-inc/      ok     18    35856    32485    3371    10        7       0      0     0       0    2929.6    7946.7
            03020833-pr-confl-inc/     ok     18    35856    32485    3371    11        7       0      0     0       0    2930.6    8047.4
BVFP        03020819-master-inc/       ok     10     3422     3062     360     7        6       0      0     0       0    1850.8    1533.1
            03020833-pr-both-inc/      ok     10     3422     3062     360     8        6       0      0     0       0    1850.7    1526.7
            03020833-pr-confl-inc/     ok     10     3422     3062     360     7        6       0      0     0       0    1852.2    1528.3
LIA         03020819-master-inc/       ok      6    25393    21716    3677     4        0       0      0     0       0      23.3     139.4
            03020833-pr-both-inc/      ok      6    25393    21716    3677     4        0       0      0     0       0      23.5     137.3
            03020833-pr-confl-inc/     ok      6    25393    21716    3677     2        0       0      0     0       0      23.7     137.5
LRA         03020819-master-inc/       ok      5    15969    15901      68     2        0       0      0     0       0      76.9     517.0
            03020833-pr-both-inc/      ok      5    15969    15901      68     3        0       0      0     0       0      75.4     515.5
            03020833-pr-confl-inc/     ok      5    15969    15901      68     4        0       0      0     0       0      76.2     517.9
QF_ABV      03020819-master-inc/       ok    949     2257      960    1297   656       22       0      0     0       0   18187.3   94124.4
            03020833-pr-both-inc/      ok    949     2255      959    1296   611       23       0      0     0       0   18136.1   94074.7
            03020833-pr-confl-inc/     ok    949     2255      959    1296   621       23       0      0     0       0   18192.2   93974.4
QF_ABVFP    03020819-master-inc/       ok     14     1960     1868      92     9        1       0      0     0       0     618.4    4013.6
            03020833-pr-both-inc/      ok     14     1960     1868      92     9        1       0      0     0       0     616.7    4048.8
            03020833-pr-confl-inc/     ok     14     1960     1868      92     8        1       0      0     0       0     619.8    4042.2
QF_ALIA     03020819-master-inc/       ok     44   421521   395114   26407    18       15       0      0     0       0    4999.3   10641.7
            03020833-pr-both-inc/      ok     44   418021   391614   26407    23       15       0      0     0       0    4996.7   10554.0
            03020833-pr-confl-inc/     ok     44   415931   389525   26406    24       15       0      0     0       0    4997.1   10640.8
QF_ANIA     03020819-master-inc/       ok      5    43429    41973    1456     2        1       0      0     0       0     519.3    1360.9
            03020833-pr-both-inc/      ok      5    43429    41973    1456     2        1       0      0     0       0     523.6    1376.8
            03020833-pr-confl-inc/     ok      5    43429    41973    1456     2        1       0      0     0       0     519.1    1368.1
QF_AUFBV    03020819-master-inc/       ok     30      497        7     490    22       17       0      0     0       0    5432.1   11434.2
            03020833-pr-both-inc/      ok     30      496        7     489    18       17       0      0     0       0    5444.0   11429.4
            03020833-pr-confl-inc/     ok     30      496        7     489    22       17       0      0     0       0    5440.7   11456.6
QF_AUFBVLIA 03020819-master-inc/       ok    327      652      329     323   166        2       0      0     0       0   11836.7   78443.1
            03020833-pr-both-inc/      ok    327      652      329     323   175        2       0      0     0       0   11872.0   79478.8
            03020833-pr-confl-inc/     ok    327      653      330     323   148        1       0      0     0       0   11871.8   79500.5
QF_AUFBVNIA 03020819-master-inc/       ok     21       42       21      21    11        0       0      0     0       0     766.6    5497.2
            03020833-pr-both-inc/      ok     21       41       20      21    13        1       0      0     0       0     773.4    5507.6
            03020833-pr-confl-inc/     ok     21       41       20      21    14        1       0      0     0       0     766.4    5497.7
QF_AUFLIA   03020819-master-inc/       ok     72  2263072  1792210  470862    42       15       0      0     0       0    5675.2   22233.3
            03020833-pr-both-inc/      ok     72  2275013  1802435  472578    45       15       0      0     0       0    5669.3   22890.0
            03020833-pr-confl-inc/     ok     72  2248580  1776952  471628    47       15       0      0     0       0    5662.6   21492.2
QF_BV       03020819-master-inc/       ok   1206    49687    43849    5838   885       41       0      0     0       0   16370.3  112169.7
            03020833-pr-both-inc/      ok   1206    49686    43849    5837   925       41       0      0     0       0   16109.0  111729.7
            03020833-pr-confl-inc/     ok   1206    49690    43851    5839   915       39       0      0     0       0   16123.3  112002.1
QF_BVFP     03020819-master-inc/       ok    114    32839    32167     672    77        0       0      0     0       0     512.9    9018.8
            03020833-pr-both-inc/      ok    114    32839    32167     672    69        0       0      0     0       0     519.1    9030.9
            03020833-pr-confl-inc/     ok    114    32839    32167     672    82        0       0      0     0       0     514.9    9028.7
QF_FP       03020819-master-inc/       ok      2       52       41      11     2        0       0      0     0       0       0.5      15.7
            03020833-pr-both-inc/      ok      2       52       41      11     2        0       0      0     0       0       0.5      15.9
            03020833-pr-confl-inc/     ok      2       52       41      11     2        0       0      0     0       0       0.5      16.1
QF_LIA      03020819-master-inc/       ok     69  2712368  2094002  618366    40       54       0      0     0       0   16915.8   40175.4
            03020833-pr-both-inc/      ok     69  2692838  2076899  615939    37       54       0      0     0       0   16928.4   39944.6
            03020833-pr-confl-inc/     ok     69  2675187  2063260  611927    23       54       0      0     0       0   16946.4   39748.3
QF_LRA      03020819-master-inc/       to     10      469      104     365     7       10       0      0     0       0    3004.3    8379.2
            03020833-pr-both-inc/      to     10      469      105     364     5       10       0      0     0       0    3005.0    8054.7
            03020833-pr-confl-inc/     to     10      467      105     362     2       10       0      0     0       0    3003.7    8251.2
QF_NIA      03020819-master-inc/       to     10  1212582  1175445   37137     8       10       0      0     0       0    3004.8    4832.1
            03020833-pr-both-inc/      to     10  1212314  1175310   37004     6       10       0      0     0       0    3004.9    4825.5
            03020833-pr-confl-inc/     to     10  1185401  1148840   36561     1       10       0      0     0       0    3006.0    4832.9
QF_UF       03020819-master-inc/       ok    766     1532     1070     462   559        0       0      0     0       0     932.7   39426.0
            03020833-pr-both-inc/      ok    766     1532     1070     462   551        0       0      0     0       0     937.8   39437.3
            03020833-pr-confl-inc/     ok    766     1532     1070     462   501        0       0      0     0       0     943.5   39411.8
QF_UFBV     03020819-master-inc/       ok   2323     5055     3332    1723  1382       10       0      0     0       0   18783.7  165610.1
            03020833-pr-both-inc/      ok   2323     5055     3332    1723  1467       10       0      0     0       0   18772.8  165461.8
            03020833-pr-confl-inc/     ok   2323     5057     3332    1725  1150       10       0      0     0       0   18952.5  165605.7
QF_UFBVLIA  03020819-master-inc/       ok     28       56       45      11    22        0       0      0     0       0       4.7     291.4
            03020833-pr-both-inc/      ok     28       56       45      11    20        0       0      0     0       0       5.0     298.1
            03020833-pr-confl-inc/     ok     28       56       45      11    21        0       0      0     0       0       4.8     297.5
QF_UFFP     03020819-master-inc/       ok      1        2        0       2     1        0       0      0     0       0       0.5      31.3
            03020833-pr-both-inc/      ok      1        2        0       2     1        0       0      0     0       0       0.5      57.6
            03020833-pr-confl-inc/     ok      1        2        0       2     1        0       0      0     0       0       0.5      58.5
QF_UFLIA    03020819-master-inc/       ok    603   432016   408813   23203   520      208       0      0     0       0   63463.6   24858.0
            03020833-pr-both-inc/      ok    603   427770   404815   22955   500      208       0      0     0       0   63476.4   24571.7
            03020833-pr-confl-inc/     ok    603   422077   399333   22744   487      208       0      0     0       0   63480.6   24662.7
QF_UFLRA    03020819-master-inc/       ok   3043    20200    12534    7666  2330       82       0      0     0       0   52333.1  256336.5
            03020833-pr-both-inc/      ok   3043    20198    12532    7666  2262       82       0      0     0       0   52453.5  255605.8
            03020833-pr-confl-inc/     ok   3043    20189    12523    7666  2193       82       0      0     0       0   52542.8  253906.4
QF_UFNIA    03020819-master-inc/       to      1    72520    66937    5583     1        1       0      0     0       0     300.3     192.2
            03020833-pr-both-inc/      to      1    72686    67103    5583     1        1       0      0     0       0     300.3     192.0
            03020833-pr-confl-inc/     to      1    73441    67858    5583     1        1       0      0     0       0     300.3     192.9
UF          03020819-master-inc/       ok   2976    79636    32924   46712  2278      481      17      0     0       0  161380.4 1245038.3
            03020833-pr-both-inc/      ok   2976    79636    32924   46712  2321      480      18      0     0       0  161323.5 1242467.6
            03020833-pr-confl-inc/     ok   2976    79636    32924   46712  2268      481      17      0     0       0  161371.6 1244312.6
UFLRA       03020819-master-inc/       ok   1038   238251        0  238251   532       40       0      0     0       0   34318.4   13756.7
            03020833-pr-both-inc/      ok   1038   238268        0  238268   505       40       0      0     0       0   34352.8   13718.5
            03020833-pr-confl-inc/     ok   1038   238269        0  238269   492       40       0      0     0       0   34332.8   13738.3
UFNIA       03020819-master-inc/       ok   3172    94928    28580   66348  2369      624       1      0     0       0  207276.9 1038711.7
            03020833-pr-both-inc/      ok   3172    94936    28580   66356  2453      624       1      0     0       0  207246.5 1037056.8
            03020833-pr-confl-inc/     ok   3172    94915    28580   66335  2318      624       1      0     0       0  207302.0 1042095.8
UFNRA       03020819-master-inc/       ok      3       10        6       4     3        0       0      0     0       0       0.4       6.7
            03020833-pr-both-inc/      ok      3       10        6       4     2        0       0      0     0       0       0.5       6.5
            03020833-pr-confl-inc/     ok      3       10        6       4     3        0       0      0     0       0       0.4       6.7
```

**Comment by ajreynol** [comment]
I suggest we make this change for conflict and lemma, but not propagateLit.  Then, I think this PR is good to merge, in spite of the incremental performance.

**Pull request merged**
