### PR TITLE
Do not rename uninterpreted constants

### LINKED ISSUE #1035: Heap-buffer-overflow in UFDT benchmarks (Bugzilla #822)
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *RESOLVED*
Severity: *critical*
Assigned to: *Andrew Reynolds*
Component: *Quantifiers*
Milestone: *1.5*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[heap_buffer_overflow.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/455_heap_buffer_overflow.smt2)_ (Example, ID 455)

On 2017-06-15 01:04:02 -0700, Andres Noetzli wrote:
> Created attachment 455
> Example
> 
> On a couple of the UFDT benchmarks, ASAN is reporting a heap\-buffer\-overflow (the competition is failing with a segfault). Attaching example. ASAN report:
> 
> \=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=
> \=\=6400\=\=ERROR: AddressSanitizer: heap\-buffer\-overflow on address 0x6020013135a8 at pc 0x000000bc3c42 bp 0x7ffdb81628f0 sp 0x7ffdb81628e8
> READ of size 8 at 0x6020013135a8 thread T0
>     \# 0 0xbc3c41 in CVC4::NodeTemplate<true>::operator\=(CVC4::NodeTemplate<false> const&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/expr/node.h:1143:3
>     \# 1 0x157a8bb in CVC4::theory::inst::InstMatch::setValue(int, CVC4::NodeTemplate<false>) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match.cpp:128:13
>     \# 2 0x291b50d in CVC4::theory::inst::InstMatchGeneratorSimple::addInstantiations(CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngine\*, int&, int, CVC4::theory::quantifiers::TermArgTrie\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match\_generator.cpp:959:7
>     \# 3 0x291c210 in CVC4::theory::inst::InstMatchGeneratorSimple::addInstantiations(CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngine\*, int&, int, CVC4::theory::quantifiers::TermArgTrie\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match\_generator.cpp:990:7
>     \# 4 0x291bdaa in CVC4::theory::inst::InstMatchGeneratorSimple::addInstantiations(CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngine\*, int&, int, CVC4::theory::quantifiers::TermArgTrie\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match\_generator.cpp:976:13
>     \# 5 0x291a8c4 in CVC4::theory::inst::InstMatchGeneratorSimple::addInstantiations(CVC4::NodeTemplate<true>, CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngine\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match\_generator.cpp:945:5
>     \# 6 0x1702763 in CVC4::theory::inst::Trigger::addInstantiations(CVC4::theory::inst::InstMatch&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/trigger.cpp:109:21
>     \# 7 0x297ef8d in CVC4::theory::quantifiers::InstStrategyAutoGenTriggers::process(CVC4::NodeTemplate<true>, CVC4::theory::Theory::Effort, int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_strategy\_e\_matching.cpp:246:29
>     \# 8 0x29aa9f6 in CVC4::theory::quantifiers::InstantiationEngine::doInstantiationRound(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/instantiation\_engine.cpp:85:29
>     \# 9 0x29abca7 in CVC4::theory::quantifiers::InstantiationEngine::check(CVC4::theory::Theory::Effort, unsigned int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/instantiation\_engine.cpp:138:7
>     \# 10 0x223aa4c in CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers\_engine.cpp:539:11
>     \# 11 0xedeb31 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/theory\_engine.cpp:618:11
>     \# 12 0x220d6a4 in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/prop/theory\_proxy.cpp:85:3
>     \# 13 0x2b98426 in CVC4::Minisat::Solver::theoryCheck(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:979:3
>     \# 14 0x2b8d52b in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:879:7
>     \# 15 0x2b9c139 in CVC4::Minisat::Solver::search(int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:1190:22
>     \# 16 0x2b9ec84 in CVC4::Minisat::Solver::solve\_() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:1412:18
>     \# 17 0x2cecf85 in CVC4::Minisat::SimpSolver::solve\_(bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/simp/SimpSolver.cc:148:18
>     \# 18 0x2bfef7d in CVC4::Minisat::SimpSolver::solve(bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/../../prop/minisat/simp/SimpSolver.h:202:10
>     \# 19 0x2bfc2ff in CVC4::prop::MinisatSatSolver::solve() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/minisat.cpp:184:28
>     \# 20 0x2200ad1 in CVC4::prop::PropEngine::checkSat() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/prop/prop\_engine.cpp:200:21
>     \# 21 0xb800af in CVC4::SmtEngine::check() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:3881:19
>     \# 22 0xb8eb3d in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:4539:48
>     \# 23 0xb8d9b7 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:4485:10
>     \# 24 0xacdbdb in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/command.cpp:297:16
>     \# 25 0xaca5ca in CVC4::Command::invoke(CVC4::SmtEngine\*, std::ostream&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/command.cpp:109:3
>     \# 26 0x50cd8a in CVC4::main::smtEngineInvoke(CVC4::SmtEngine\*, CVC4::Command\*, std::ostream\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/command\_executor.cpp:179:5
>     \# 27 0x50ad95 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/command\_executor.cpp:104:14
>     \# 28 0x50a56e in CVC4::main::CommandExecutor::doCommand(CVC4::Command\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/command\_executor.cpp:87:12
>     \# 29 0x515a33 in runCvc4(int, char\*\*, CVC4::Options&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/driver\_unified.cpp:535:18
>     \# 30 0x509385 in main /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/main.cpp:55:12
>     \# 31 0x7fcca5ffe82f in \_\_libc\_start\_main /build/glibc\-9tT8Do/glibc\-2.23/csu/../csu/libc\-start.c:291
>     \# 32 0x434dc8 in \_start (/barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/cvc4\+0x434dc8)
> 
> 0x6020013135a8 is located 8 bytes to the left of 8\-byte region [0x6020013135b0,0x6020013135b8)
> allocated by thread T0 here:
>     \# 0 0x5064c0 in operator new(unsigned long) (/barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/cvc4\+0x5064c0)
>     \# 1 0xc6e1ab in \_\_gnu\_cxx::new\_allocator<CVC4::NodeTemplate<true> >::allocate(unsigned long, void const\*) /usr/bin/../lib/gcc/x86\_64\-linux\-gnu/5.4.0/../../../../include/c\+\+/5.4.0/ext/new\_allocator.h:104:27
>     \# 2 0xc6e14b in \_\_gnu\_cxx::\_\_alloc\_traits<std::allocator<CVC4::NodeTemplate<true> > >::allocate(std::allocator<CVC4::NodeTemplate<true> >&, unsigned long) /usr/bin/../lib/gcc/x86\_64\-linux\-gnu/5.4.0/../../../../include/c\+\+/5.4.0/ext/alloc\_traits.h:182:14
>     \# 3 0xc6df82 in std::\_Vector\_base<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > >::\_M\_allocate(unsigned long) /usr/bin/../lib/gcc/x86\_64\-linux\-gnu/5.4.0/../../../../include/c\+\+/5.4.0/bits/stl\_vector.h:170:20
>     \# 4 0xc6d5c8 in std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > >::\_M\_insert\_aux(\_\_gnu\_cxx::\_\_normal\_iterator<CVC4::NodeTemplate<true>\*, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > >, CVC4::NodeTemplate<true> const&) /usr/bin/../lib/gcc/x86\_64\-linux\-gnu/5.4.0/../../../../include/c\+\+/5.4.0/bits/vector.tcc:353:24
>     \# 5 0xbbbaa1 in std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > >::push\_back(CVC4::NodeTemplate<true> const&) /usr/bin/../lib/gcc/x86\_64\-linux\-gnu/5.4.0/../../../../include/c\+\+/5.4.0/bits/stl\_vector.h:925:4
>     \# 6 0x1578f64 in CVC4::theory::inst::InstMatch::InstMatch(CVC4::NodeTemplate<false>) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match.cpp:32:5
>     \# 7 0x291a83e in CVC4::theory::inst::InstMatchGeneratorSimple::addInstantiations(CVC4::NodeTemplate<true>, CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngine\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_match\_generator.cpp:943:15
>     \# 8 0x1702763 in CVC4::theory::inst::Trigger::addInstantiations(CVC4::theory::inst::InstMatch&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/trigger.cpp:109:21
>     \# 9 0x297ef8d in CVC4::theory::quantifiers::InstStrategyAutoGenTriggers::process(CVC4::NodeTemplate<true>, CVC4::theory::Theory::Effort, int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/inst\_strategy\_e\_matching.cpp:246:29
>     \# 10 0x29aa9f6 in CVC4::theory::quantifiers::InstantiationEngine::doInstantiationRound(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/instantiation\_engine.cpp:85:29
>     \# 11 0x29abca7 in CVC4::theory::quantifiers::InstantiationEngine::check(CVC4::theory::Theory::Effort, unsigned int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers/instantiation\_engine.cpp:138:7
>     \# 12 0x223aa4c in CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/quantifiers\_engine.cpp:539:11
>     \# 13 0xedeb31 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/theory/theory\_engine.cpp:618:11
>     \# 14 0x220d6a4 in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/prop/theory\_proxy.cpp:85:3
>     \# 15 0x2b98426 in CVC4::Minisat::Solver::theoryCheck(CVC4::theory::Theory::Effort) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:979:3
>     \# 16 0x2b8d52b in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:879:7
>     \# 17 0x2b9c139 in CVC4::Minisat::Solver::search(int) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:1190:22
>     \# 18 0x2b9ec84 in CVC4::Minisat::Solver::solve\_() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/core/Solver.cc:1412:18
>     \# 19 0x2cecf85 in CVC4::Minisat::SimpSolver::solve\_(bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/simp/SimpSolver.cc:148:18
>     \# 20 0x2bfef7d in CVC4::Minisat::SimpSolver::solve(bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/../../prop/minisat/simp/SimpSolver.h:202:10
>     \# 21 0x2bfc2ff in CVC4::prop::MinisatSatSolver::solve() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/prop/minisat/../../../../../../src/prop/minisat/minisat.cpp:184:28
>     \# 22 0x2200ad1 in CVC4::prop::PropEngine::checkSat() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/prop/prop\_engine.cpp:200:21
>     \# 23 0xb800af in CVC4::SmtEngine::check() /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:3881:19
>     \# 24 0xb8eb3d in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:4539:48
>     \# 25 0xb8d9b7 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/smt\_engine.cpp:4485:10
>     \# 26 0xacdbdb in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/command.cpp:297:16
>     \# 27 0xaca5ca in CVC4::Command::invoke(CVC4::SmtEngine\*, std::ostream&) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/smt/command.cpp:109:3
>     \# 28 0x50cd8a in CVC4::main::smtEngineInvoke(CVC4::SmtEngine\*, CVC4::Command\*, std::ostream\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/command\_executor.cpp:179:5
>     \# 29 0x50ad95 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command\*) /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/main/../../../../../src/main/command\_executor.cpp:104:14
> 
> SUMMARY: AddressSanitizer: heap\-buffer\-overflow /barrett/scratch/noetzli/CVC4\_dbg/builds/x86\_64\-pc\-linux\-gnu/debug\-staticbinary\-proof/src/../../../../src/expr/node.h:1143:3 in CVC4::NodeTemplate<true>::operator\=(CVC4::NodeTemplate<false> const&)
> Shadow bytes around the buggy address:
>   0x0c048025a660: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c048025a670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c048025a680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c048025a690: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c048025a6a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> \=>0x0c048025a6b0: fa fa fa fa fa[fa]00 fa fa fa 00 00 fa fa fd fa
>   0x0c048025a6c0: fa fa 00 00 fa fa fd fa fa fa fd fd fa fa fd fd
>   0x0c048025a6d0: fa fa 00 00 fa fa fd fa fa fa fd fa fa fa fd fa
>   0x0c048025a6e0: fa fa 00 00 fa fa fd fa fa fa 00 fa fa fa fd fa
>   0x0c048025a6f0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
>   0x0c048025a700: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07
>   Heap left redzone:       fa
>   Heap right redzone:      fb
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack partial redzone:   f4
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
> \=\=6400\=\=ABORTING

On 2017-06-15 01:05:58 -0700, Andres Noetzli wrote:
> Looks like the issue is that one of the children of t does not existing anymore:
> 
> https://github.com/CVC4/CVC4/blob/master/src/theory/quantifiers/inst_match_generator.cpp#L95

On 2017-06-15 09:34:41 -0700, Andrew Reynolds wrote:
> For attachment 455 above, CVC4 no longer crashes after https://github.com/CVC4/CVC4/commit/3344979103bcec622276fca7c2a21cc0945f6c56
> 
> However this is likely coincidental (I did not specifically address this bug in that commit).
> 
> Can you give me a full list of benchmarks with this error so I can see if others are still crashing?
> 
> Thanks,
> Andy

On 2017-06-15 10:51:57 -0700, Andrew Reynolds wrote:
> Revisiting the original problem, the source of this bug is likely fixed by:
> 
> https://github.com/CVC4/CVC4/commit/209b08887bc55349880b9ed6d858e23637267dee
> 
> but I'd like to confirm.
> 
> \-Andy

On 2017-06-15 11:20:45 -0700, Andres Noetzli wrote:
> It is somewhat difficult to identify the complete set of benchmarks because they are simply appearing as segfaults in the logs. However, I tested the inputs that segfaulted and they seem to be fine now on the current master. I am compiling a new competition version with asserts and will run on UFDT.

On 2017-06-15 22:20:24 -0700, Andres Noetzli wrote:
> All the UFDT benchmarks are now working as expected (except the 541 benchmarks that will be removed). Marking this bug as fixed.

### PR DESCRIPTION
**Pull request by ajreynol**
For some reason, some characters were manually replaced by underscores in the names of uninterepreted constants. This has caused naming problems in models for users.

Fixes #1035.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Hmm, but then our output can be invalid, no? Can we maybe just escape the variable names if they use any non-[A-Za-z0-9] characters?

**Comment by ajreynol** [comment]
So you mean adding "|" before and after if they have a non-[A-Za-z0-9] character?

**Comment by 4tXJ7f** [comment]
Yes, although I just checked the standard and I think that `~ ! @ $ % ^ & * _ - + = < > . ? /` are legal too (in addition to [A-Za-z0-9]) without escaping. Note that the vertical bars "|" may not contain another "|" or "\".

**Comment by ajreynol** [comment]
I think what you're saying above is actually a smt2 printing issue.  There is a standard way of handling this in the smt2 printer "maybeQuoteSymbol".  I'll update the code to do this.

**Pull request merged**
