### PR TITLE
Further standardization of strings statistics

### PR DESCRIPTION
**Pull request by ajreynol**
Also eliminates use of raw output channel in strings.

### CODE REVIEW

**Review by nafur — APPROVED** [review]
LGTM. Have we checked whether this changes the solver behaviour in any way?

**Comment by ajreynol** [comment]
It does change the behavior slightly (actually one regression needed an option change), I could do a quick QF_SLIA run, what do you think?

**Comment by nafur** [comment]
I'd prefer to check this.

**Comment by ajreynol** [comment]
You were right to worry, there is a performance regression, I will look into this.

**Comment by ajreynol** [comment]
```
                           Configuration  #unsat      time    #sat      time #solved    #total
                   CVC4-031221_strings_d   26533    5067.4   42103   35283.3     68636     69903
               CVC4-031221-sss_strings_d   26533   5097.71   42000   35312.5     68533     69903
               CVC4-031521-sss_strings_d   26532   5038.34   42119   35899.9     68651     69903

For unsatisfiable : 
                   CVC4-031221_strings_d       X       0       1
               CVC4-031221-sss_strings_d       0       X       1
               CVC4-031521-sss_strings_d       0       0       X

For satisfiable : 
                   CVC4-031221_strings_d       X     107       0
               CVC4-031221-sss_strings_d       4       X       2
               CVC4-031521-sss_strings_d      16     121       X
```
CVC4-031521-sss_strings_d = this PR after fix to performance issue, +16-1 on SMT-LIB QF_SLIA+QF_S, 60 second timeout.

**Pull request merged**
