### PR TITLE
Check unsat cores in regressions also without LFSC

### PR DESCRIPTION
**Pull request by 4tXJ7f**
When moving the LFSC checker out of the CVC4 repository in commit
dfa69ff98a14fcc0f2387e59a0c9994ef440e7d0, we disabled checking unsat
cores when CVC4 was compiled without LFSC due to the complexity of the
regression script. This commit changes the new(-ish) Python regression
script to check unsat cores even when CVC4 was compiled without LFSC.
This is done by having two separate flags, --with-lfsc and
--enable-proof, for the regression script that mirror the configuration
flags. The regression script performs unsat cores and proofs checks
based on those flags.

Additionally, this commit changes the regression script to check proofs
and unsat cores in two independent runs. Testing them in a single run
masked issues #1953 and #1954.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Note that regressions will fail due to the open issues mentioned above.

**Comment by aniemetz** [comment]
So this PR should only be merged in when the open issues are resolved?

**Comment by 4tXJ7f** [comment]
Yeah, I already submitted two PRs to fix the issues #1957 (awaiting review) and #1958 (merged).

**Comment by 4tXJ7f** [comment]
One more fix in #1976. Now it should hopefully work out :)

**Pull request merged**
