### PR TITLE
Disable algebraic BV subtheory by default and make experimental.

### PR DESCRIPTION
**Pull request by mpreiner**

### CODE REVIEW

**Comment by ajreynol** [comment]
Does this fix #5370 or other issues related to theory combination with BV?

**Comment by mpreiner** [comment]
No it does not fix the issues since passing `--bv-algebraic-solver` will still trigger it. The algebraic solver will be phased out with the lazy BV solver and therefore is a won't fix.

**Comment by ajreynol** [comment]
Right, it doesn't fix, but with this PR I would recommend that this issue could be moved to cvc4-projects, since it only triggers on an experimental option.

Btw, I checked, with this PR, we do not give wrong models for #5370, #5462, #4780 by default.

**Comment by ajreynol** [comment]
@mpreiner do any regressions change run time significantly?  If there are no performance regressions, this looks good to me.

**Comment by mpreiner** [comment]
@ajreynol there is little to no improvement with the algebraic solver (QF_ABV is even worse):

```
                         total  solved    sat  unsat  timeout  memout  uniq   time_cpu
config                                                                          
run-noalgebraic/   58087   53592  23796  29796     4443      52    94  1639573.1
run-algebraic/     58087   53573  23767  29806     4455      59    75  1641134.1

                             total  solved    sat  unsat  timeout  memout  uniq   time_cpu
benchmark config                                                                          
QF_ABV    run-algebraic/     15084   14424   9888   4536      642      18    37   264246.4
          run-noalgebraic/   15084   14447   9909   4538      619      18    60   255394.3
QF_AUFBV  run-algebraic/        56      32      6     26       22       2     0     6902.6
          run-noalgebraic/      56      32      6     26       22       2     0     6915.7
QF_BV     run-algebraic/     41713   37926  13228  24698     3750      37    38  1352809.9
          run-noalgebraic/   41713   37922  13236  24686     3761      30    34  1360197.8
QF_UFBV   run-algebraic/      1234    1191    645    546       41       2     0    17175.2
          run-noalgebraic/    1234    1191    645    546       41       2     0    17065.3

```

**Review by ajreynol — APPROVED** [review]

**Pull request merged**
