### PR TITLE
Multi-goal optimization support

### PR DESCRIPTION
**Pull request by Ouyancheng**
This PR includes support for multiple-objective optimization, goal could be combined using Box, Lexicographic and Pareto strategies. 
All three strategies are tested. Unit tests included. 

Also (IMPORTANT) fixed two critical logical bugs in BV optimizer!

### CODE REVIEW

**Comment by Ouyancheng** [comment]
For review, the diff view seems a bit messy. But most of the code is just refactoring -- I mainly replaced most of the if-statements on enums with switch statements. so the code in bitvector_optimizer.cpp and integer_optimizer.cpp are mainly refactored without major changes. 
And the new code are just three simple functions in optimization_solver.cpp : optimizeBoxNaive, optimizeLexIterative and optimizeParetoNaive.

**Comment by Ouyancheng** [comment]
Or if you want me to break it into chunks I could

**Comment by Ouyancheng** [comment]
Since no one's replying, THIS IS CLOSED!

**Comment by mpreiner** [comment]
@Ouyancheng We agreed on Monday to split this PR into smaller chunks to make it easier to review. Please do so and submit new PRs.

**Comment by Ouyancheng** [comment]
will do afterwards.

**Pull request closed without merging**
