### PR TITLE
CMS: Update to version 5.8.0.

### PR DESCRIPTION
**Pull request by aniemetz**

### CODE REVIEW

**Comment by aniemetz** [comment]
For the sake of completeness, here are the numbers on QF_BV with `--bitblast=eager`, 1200s time limit, 8GB memory limit:
```
                           status  result  solved    sat  unsat   best  timeout  memout  error  uniq  disagr   time_cpu     memory
config                                                                                                                            
2020-09-01-cvc4-cms-5.8.0/     ok   41713   40246  14001  26245   8103     1432      35      0   205       0  2487018.0  4266852.1
2020-09-01-cvc4-cms-5.6.3/     ok   41713   40096  13866  26230  32198     1584      33      0    55       0  2588301.1  4151284.1
```
@mpreiner @msoos

**Comment by msoos** [comment]
Woe, thank you so much! Do you know what the numbers for CaDiCaL are?

**Comment by aniemetz** [comment]
@msoos 
```
                           status  result  solved    sat  unsat   best  timeout  memout  error  uniq  disagr   time_cpu     memory
config                                                                                                                            
2020-09-08-cvc4-cadical/       ok   41713   40668  14263  26405   8303     1009      36      0   418       0  1705664.0  4113060.9
2020-09-01-cvc4-cms-5.8.0/     ok   41713   40246  14001  26245   4221     1432      35      0    19       0  2487018.0  4266852.1
2020-09-01-cvc4-cms-5.6.3/     ok   41713   40096  13866  26230  28195     1584      33      0     9       0  2588301.1  4151284.1
```

**Comment by msoos** [comment]
Wow, thank you so much! So I still have some way to go :) I'll play with it
and see how far I can push it. Thank you so much again,

Mate

**Pull request merged**
