### PR TITLE
Avoid substituting Boolean term variables

### LINKED ISSUE #3020: Surprising slow performance on very small benchmark with arrays of booleans
CVC4 has trouble solving a small benchmark that includes arrays of booleans (a silly thing to do but technically supported I believe). 

What's interesting is that running with `--simplification=none`, it is solved instantly (it's `sat`).

However, trying with the following options, it does not terminate within 5 minutes on my laptop:
* no command line flags
* `--arrays-weak-equiv`
* `--ite-simp --simp-with-care --repeat-simp --arrays-weak-equiv`

If however, you use bit-vectors of size one instead of booleans, CVC4 solves it quickly with any of those options.

[array-bool.smt2.tar.gz](https://github.com/CVC4/CVC4/files/3218455/array-bool.smt2.tar.gz)
[array-bv1.smt2.tar.gz](https://github.com/CVC4/CVC4/files/3218538/array-bv1.smt2.tar.gz)

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Fixes #3020. Boolean terms that appear in other terms, e.g. a Boolean
array index, are replaced by `BOOLEAN_TERM_VARIABLE`s to make sure that
they are handled properly in theory combination. When doing this
replacement, an equality of the form `(= <Boolean term> <Boolean term
variable)` is added to the assertions. The problem was that
`Theory::ppAssert()` would derive a substitution when this equality was
registered. The commit fixes the problem by not allowing to add
substitutions for `BOOLEAN_TERM_VARIABLE`s.

@makaimann

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Note: I am not sure if this is the best way to solve the issue. If you have a better idea, please let me know.

**Comment by ajreynol** [comment]
Do you know the performance impact of this PR on a larger set of examples? It looks feasible to me that this could be a good idea (although I don't have any specific intuition on why).

**Comment by 4tXJ7f** [comment]
Hmm, I didn't do any performance tests yet but I'll do some. However, I was under the impression that it is _required_ to have `BOOLEAN_TERM_VARIABLES` instead of Boolean terms within other theory terms because it is needed for theory combination to work correctly. Did I misunderstand?

**Comment by 4tXJ7f** [comment]
I ran on UFDT (with `--full-saturate-quant`) hoping that there would be datatypes with Boolean arguments that would make a difference but there seems to be no difference:
```
         DIRECTORY |                                    uf_dt_master |                                    uf_dt_pr3022 | 
         Benchmark |  Stat Slvd  Tot   To Mo Err    Cpu[s]   Mem[MB] |  Stat Slvd  Tot   To Mo Err    Cpu[s]   Mem[MB] | 
      cdt-cade2015 |    ok 2045 3885 1839  1   0 2219633.9  938502.4 |    ok 2045 3885 1839  1   0 2219384.0  942640.6 | 
 rec-fun-ijcar2016 |    ok   96  642  520  6   0  629217.7  329487.6 |    ok   96  642  520  6   0  629177.8  330913.6 | 
          __totals |    ok 2141 4527 2359  7   0 2848851.6 1267990.0 |    ok 2141 4527 2359  7   0 2848561.8 1273554.2 | 
```

On QF_ABV (with `--arrays-weak-equiv`), we have a similar picture:
```
          DIRECTORY |                                  qf_abv_master |                                  qf_abv_pr3022 | 
          Benchmark |  Stat  Slvd   Tot  To Mo Err   Cpu[s]  Mem[MB] |  Stat  Slvd   Tot  To Mo Err   Cpu[s]  Mem[MB] | 
          2018-Mann |    to     0     5   5  0   0   6000.7  10364.1 |    to     0     5   5  0   0   6000.7  10490.3 | 
          2019-Mann |    to     0     1   1  0   0   1200.2   1733.5 |    to     0     1   1  0   0   1200.2   1731.1 | 
  2019-Wolf-fmbench |    ok     1    16  15  0   0  18919.4  10535.7 |    ok     1    16  15  0   0  18926.3  10460.2 | 
           bench_ab |    ok   119   119   0  0   0      6.5    418.6 |    ok   119   119   0  0   0      5.0    381.2 | 
         bmc-arrays |    ok    37    39   2  0   0   3103.5   6374.4 |    ok    37    39   2  0   0   3101.3   6370.2 | 
     brummayerbiere |    ok   245   293  48  0   0  76625.9  85539.3 |    ok   245   293  48  0   0  76259.1  85021.0 | 
    brummayerbiere2 |    ok    15    22   5  2   0   8167.8  35249.7 |    ok    15    22   5  2   0   8157.8  35239.7 | 
    brummayerbiere3 |    ok    10    10   0  0   0      1.4    124.9 |    ok    10    10   0  0   0      1.3    127.6 | 
              btfnt |    ok     1     1   0  0   0    183.4    206.8 |    ok     1     1   0  0   0    182.9    219.4 | 
              calc2 |    ok    17    36  19  0   0  28773.1  11119.1 |    ok    18    36  18  0   0  28620.8  11118.5 | 
       dwp_formulas |    ok  5762  5765   3  0   0   8661.6  66132.2 |    ok  5762  5765   3  0   0   8707.4  66385.8 | 
                ecc |    ok    51    52   1  0   0   1377.5   8925.3 |    ok    51    52   1  0   0   1360.0   8917.7 | 
                egt |    ok  7719  7719   0  0   0     61.2   4243.9 |    ok  7719  7719   0  0   0     55.8   4206.4 | 
              jager |    mo     0     2   0  2   0    500.2  16404.7 |    mo     0     2   0  2   0    543.2  16398.5 | 
 klee-selected-smt2 |    ok   595   595   0  0   0   3583.8  39657.0 |    ok   595   595   0  0   0   3455.5  39648.3 | 
               pipe |    ok     1     1   0  0   0    988.9   1083.5 |    ok     1     1   0  0   0    935.7   1083.4 | 
           platania |    ok   242   275  33  0   0  41362.8  27626.5 |    ok   242   275  33  0   0  41322.7  27297.0 | 
  sharing-is-caring |    ok    40    40   0  0   0      0.0      0.0 |    ok    40    40   0  0   0      0.0      0.0 | 
                stp |    ok    38    40   1  1   0   4921.6  52691.8 |    ok    38    40   1  1   0   4814.6  52767.1 | 
        stp_samples |    ok    52    52   0  0   0      2.2    320.6 |    ok    52    52   0  0   0      3.6    398.6 | 
           __totals |    ok 14945 15083 133  5   0 204441.5 378751.6 |    ok 14946 15083 132  5   0 203653.8 378262.0 | 
```

The difference is just a single benchmark close to timeout:
```
                                      DIRECTORY |                   qf_abv_master |                   qf_abv_pr3022 | 
                                      Benchmark |  Stat  RES Exit  Cpu[s] Mem[MB] |  Stat  RES Exit  Cpu[s] Mem[MB] | 
 calc2-calc2_sec2_shifter_mult_bmc15.atlas.smt2 |    to    -    2  1200.1   205.9 |    ok   20    0 1177.27   205.7 | 
```

**Comment by 4tXJ7f** [comment]
Any other ideas for benchmarks to run? QF_DT is probably too easy.

**Comment by ajreynol** [comment]
Thanks for running these experiments, this looks good to me.

**Comment by 4tXJ7f** [comment]
Should we consider backporting this fix for 1.7.1? How bad is it for theory combination if we don't have `BOOLEAN_TERM_VAR`s, i.e. could we end up with the wrong answer?

**Pull request merged**
