### PR TITLE
Miscellaneous cleanup for CegConjectureProcess.

### PR DESCRIPTION
**Pull request by timothy-king**

### CODE REVIEW

**Comment by ajreynol** [comment]
What is the purpose of this pull request? I already several changes in the queue fo CegProcessConjecture that are not consistent with these changes.

**Comment by timothy-king** [comment]
> What is the purpose of this pull request?

This PR is a few unrelated changes to CegConjectureProcess. The purpose of the changes is code cleanup. A summary of the changes in decreasing order of importance:
1. Adds 3 missing includes to `src/theory/quantifiers/sygus_process_conj.h`. The standard IWYU arguments apply.
2. Switches several members of `CegConjecture` to use `unique_ptrs<>`. This clarifies their memory ownership.
3. Adds const specifiers that can be added to `simplify` and `initialize`. This tightens the contract to what the functions currently do. I assumed these missing were oversights.
4. Removes a redundant default constructor, destructor and public access specifier from CegSynthFunProcessInfo. Saves 3 lines of vertical space in a header and allows [aggregate-initialization in C++11](http://en.cppreference.com/w/cpp/language/aggregate_initialization).
5. Switches base and conjuncts variables in `CegConjectureProcess::initialize(...)` to a declarative style and dropping the # of vertical lines from 23 to 5. 
6. Eliminating currently dead code. Previously lines 73-78.

I probably should have split these up instead of in a single PR.

> CegProcessConjecture that are not consistent with these changes.

Which changes are inconsistent and in what way? I can drop some of these if I know which.

**Comment by ajreynol** [comment]
Pull request #1286 was intended to provide an outline of the CegConjectureProcess class.  Since we're trying to keep the commits small I was breaking this up into two....infrastructure, then contents of CegConjectureProcess.  The ::initialize(...) function had a rough sketch of how I thought this function would work, but several sygus benchmarks I have been looking at in the past few days has made me rethink this.  So changes 3-6 would not be directly applicable, although I can keep them in mind in my next PR for CegConjectureProcess.

More generally my concern is that these kinds of changes to classes that are being rapidly developed have a high likelihood of conflicts.  Perhaps it'd be helpful if you ask which files (for instance in quantifiers) are relevant.  Or even suggest changes for me to incorporate, say if you want coverity issues addressed.

Regardless, I'm fine with changes 1 and 2.

**Comment by ajreynol** [comment]
Pull request #1311 addresses most of the points from this.

**Comment by timothy-king** [comment]
Opened #1324 for 2.

**Pull request closed without merging**
