### PR TITLE
Reordering how corder gets filled. Removes a compiler warning about a…

### PR DESCRIPTION
**Pull request by timothy-king**
…n unsigned comparison against 0.

### CODE REVIEW

**Comment by ajreynol** [comment]
I will fix the unsigned comparison on a separate PR (somehow "inc" was changed from "int" -> "unsigned").   I have an open issue to refactor/clean this class (#1250).

**Comment by ajreynol** [comment]
I've fixed this on #1260.
I suggest closing this PR when that one is merged.

**Comment by ajreynol** [comment]
#1260 was merged, let me know if it is okay to merge this PR.

**Comment by timothy-king** [comment]
#1260 covered what this was fixing in a different way.

**Pull request closed without merging**
