### PR TITLE
New clang-format style based on the Google style.

### PR DESCRIPTION
**Pull request by mpreiner**
I added everyone as reviewer since this should be a discussion between all of us.

After discussing the code style with Aina and Andres I'll go ahead an propose a new .clang-format style based on the Google style. These are small modifications to the Google style that adds newlines before braces and tries to be more consistent with the parameter/argument packing.

Here are some examples:

```
namespace ... {

if (c) {
 ...
} else {
 ...
}

for (...) {
 ...
}

}
```
will be formatted as
```
namespace ... {

if (c)
{
 ...
}
else
{
 ...
}

for (...)
{
 ...
}

} 
```

For the parameter/argument packing e.g.
```
T function_name(T1 a, T2 b, T3 c)
```
If it does not fit into one line, but the parameters are then it gets formatted to
```
T function_name(
    T1 a, T2 b, T3 c)
```
Else it will be formatted such that every parameter will be in a separate line:
```
T function_name(T1 a,
                T2 b,
                T3 c)
```
If e.g. ```T3 c``` does not fit into the line with the current indentation it formats the code as
```
T function_name(
    T1 a,
    T2 b,
    T3 c)
```

If you have any suggestions or wishes for code format style, let me know.

### CODE REVIEW

**Comment by martin-cs** [comment]
On Thu, 2017-10-19 at 00:06 +0000, Mathias Preiner wrote:
> I added everyone as reviewer since this should be a discussion between all of us.
> 
> After discussing the code style with Aina and Andres I'll go ahead an propose a new .clang-format style based on the Google style. These are small modifications to the Google style that adds newlines before braces and tries to be more consistent with the parameter/argument packing.

It's crazy but I've just spent the last week arguing about exactly this
change for CPROVER.  Some things we have learnt:

*. There is a way of applying clang-format on a diff.

*. You can then use this to reformat a branch of commits or get the CI
to spit out a patch to correct things.

*. clang-format output may not be stable between versions even with the
same input.

*. Not all formatting options are supported; there are some obvious
styles that are not possible with the config.

*. Applying it to the code base as a whole is a great way of getting
your external collaborators to say "merge that and I will fork your
project".  However applying it incrementally is a great idea that
everyone can get behind.

Hope that saves you ... at least a week of arguing.

Cheers,
 - Martin

**Comment by aniemetz** [comment]
Applying it incrementally is what we are currently already doing (the old format). And that's also the plan for the future.

**Comment by timothy-king** [comment]
My 2cents. I would prefer being more conservative with vertical space than these proposed changes.

> if (c)
> {
>  ...
> }
> else
> {
>  ...
> }
IMO This wastes 3 lines on braces for no gain in readability in the majority of cases. This can only really help when the if condition has gotten out of control and one can't tell where the condition ends and the body begins.

> for (...)
> {
>  ...
> }
This wastes 1 line.

I am not sure there is much of a point in debating preferences though. Just count me as a nay vote on this.

**Comment by ajreynol** [comment]
I agree with Tim, for the same reasons.

**Comment by aniemetz** [comment]
> IMO This wastes 3 lines on braces for no gain in readability in the majority of cases. This can only really help when the if condition has gotten out of control and one can't tell where the condition ends and the body begins.

And that's exactly the problem. We do have lots of cases, where if-then-else chains got out of hand and the current style makes them unreadable.

I'm all **for** "wasting space" if it helps readability. IMO structuring code into blocks, with or without braces, helps readability.

**Comment by mpreiner** [comment]
I agree with Aina. If we achieve better readability we should waste more space.

**Comment by 4tXJ7f** [comment]
I am fine either way.

**Comment by timothy-king** [comment]
> I'm all for "wasting space" if it helps readability. 
> If we achieve better readability we should waste more space.

I agree with these points. I would describe it as 'using the space' in such cases.

I disagree with the claim that the proposed change will improve readability. I do not think we will achieve consensus on this point. So we should have a decision making process that can proceed without consensus. Voting or an executive decision by Clark both make sense to me in this circumstance.

> And that's exactly the problem. We do have lots of cases, where if-then-else chains got out of hand and the current style makes them unreadable.

I am not sure we are talking about the same thing. To clarify, my point was about the *condition* "c" in "if (c)" not the blocks or the if-else-chains themselves. Once conditions go over +2 lines and are a bit wide, then I agree that they start getting hard to read when the "{" is on the same line as the closing ")" of an if. (+3 lines is where the problems really start though.) An [okayish] example from my own code of what I mean: https://github.com/CVC4/CVC4/blob/master/src/theory/arith/constraint.cpp#L1736
A better way of addressing this case is to decompose the condition into functions.

**Comment by aniemetz** [comment]
Oh, it seems that indeed we were not talking about the same thing. I was talking about if-then-else chains like this one, e.g., 
[https://github.com/CVC4/CVC4/blob/master/src/theory/arith/constraint.cpp#L1736](https://github.com/CVC4/CVC4/blob/master/src/theory/arith/constraint.cpp#L1736), where it is extremely hard to distinguish where one (else) if block begins/ends.

Well, it was to be expected that we won't reach a point where all of us agree ;-)
So yes, I also think that we need to decide on a decision process.

**Comment by aniemetz** [comment]
Edit: Fixed the link in my last comment, c&p from the wrong tab. Here's the correct link again:
https://github.com/CVC4/CVC4/blob/9af7e38d6f0b3d01dea795a4847153047ac87f6e/src/theory/quantifiers/bv_inverter.cpp#L305

**Comment by barrettcw** [comment]
Hi all-

So it looks like we have 2 for and 2 against with one neutral party.  That
means I have to be the bad guy here and make an executive decision.  First
let me say that I can see both sides: certainly the proposed changes
introduce more vertical space.  On the other hand, some of the examples
pointed out (and others I can find in the code base) really do make the
code harder to understand.  Given these two trade-offs, I think I would
like to prioritize readability over vertical space.  We should be able to
tolerate a bit of cost in vertical space if it improves readability which
in many cases I believe it does.  Of course, we should take other measures
to improve readability as well, but I believe this does help.  That said, I
have also recommended that we *do* allow blocks that all fit on one line to
stay on one line, as this does save vertical space without sacrificing
readability in my opinion.

I know that coding styles and preferences are strongly-held by everyone.
So for those disappointed by this decision, I can only ask that you try to
be flexible, recognizing that all of us have to read each other's code and
we will all have to deal with code that has not been written the way we
would write it.

-Clark

**Pull request merged**
