### PR TITLE
Makes the new row propagation system default

### PR DESCRIPTION
**Pull request by HanielB**
By running on all SMT-LIB benchmarks which involve any kind of arithmetic logic (a total of 97285 benchmarks) we have the following results, with 300s timeout:

**new-prop** vs **default** is +2386 / - 2298, solving in total 68870 benchmarks against 68782.

On the attached plots we can see clear trends favoring new-prop:

[cactus_comp-default_vs_new-prop.csv.pdf](https://github.com/CVC4/CVC4/files/2298204/cactus_comp-default_vs_new-prop.csv.pdf)
[scatter_comp-default_vs_new-prop.csv.pdf](https://github.com/CVC4/CVC4/files/2298205/scatter_comp-default_vs_new-prop.csv.pdf)

A breakdown per logic of gains/losses:

```
| Logic   | Gain | Loss | Net |
|---------+------+------+-----|
| LRA     |   15 |   15 |   0 |
| UFLIA   |    5 |    4 |   1 |
| UFNIA   |    8 |    7 |   1 |
| QF_IDL  |   71 |   25 |  46 |
| QF_LIA  |   63 |   64 |  -1 |
| QF_LRA  |   74 |    2 |  72 |
| QF_NIA  | 1937 | 1973 | -36 |
| QF_NRA  |  206 |  203 |   3 |
| QF_ALIA |    0 |    1 |  -1 |
| UFNRA   |    5 |    1 |   4 |
| AUFLIA  |    1 |    3 |  -2 |
| AUFNIA  |    1 |    0 |   1 |
|---------+------+------+-----|
| Total   | 2386 | 2298 |  88 |
|---------+------+------+-----|
```

The biggest variations are on QF_NRA and QF_NIA, but that seems to be expected given the heuristic nature of our solving methods in these logics.

The data is available here: 
[data.zip](https://github.com/CVC4/CVC4/files/2298722/data.zip)

Using this option by default is work towards addressing #2305

### CODE REVIEW

**Comment by ajreynol** [comment]
@timothy-king , you'll be interested in this.

**Comment by ajreynol** [comment]
I think the PR is still failing regressions

**Comment by HanielB** [comment]
Fixed it. It was another nl benchmark

**Comment by HanielB** [comment]
I did a debug run on the same benchmarks also with 300s timeout and there were two assertion failures, but these are about a known issue already fixed in PR #2099

**Comment by timothy-king** [comment]
@ajreynol My only real contribution to make is that similar tests should be done on incremental benchmarks too.

**Comment by HanielB** [comment]
I'll evaluate on incremental benchmarks as well, thanks @timothy-king

**Comment by HanielB** [comment]
Of the 6122 incremental benchmarks of SMT-LIB that have any kind of arithmetic logic both configurations solve the same 6076 benchmarks. There are minimal solving time differences, and on average **new-prop** is 0.1% slower.  A debug run had no errors.

**Comment by timothy-king** [comment]
No errors on debug runs and performance difference is noise. This seems fine.

**Pull request merged**
