### PR TITLE
Commenting out throw specifiers for DeltaRationExceptions.

### PR DESCRIPTION
**Pull request by timothy-king**
These functions can be cleaned up later.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
What kind of cleanup are you envisioning? Could we open an issue for that?

**Comment by timothy-king** [comment]
The cleanup is to change these to Maybe<>'s or to update the documentation. Not worth an issue IMO. They are self documenting as needing to be addressed.

**Comment by 4tXJ7f** [comment]
I went ahead and created an issue to have a reminder that we clean it up. I am just worried that we otherwise forget about it.

**Comment by timothy-king** [comment]
Sounds good.

**Pull request merged**
