### PR TITLE
Check for sigaltstack in configure

### PR DESCRIPTION
**Pull request by cpitclaudel**
emscripten doesn't provide sigaltstack (cc @4tXJ7f).  This PR simply disables it if it isn't available.

### CODE REVIEW

**Comment by 4tXJ7f** [comment]
Looks good. I just have one comment: `sigaction(SIGILL, &act4, NULL)` is inside the `#ifdef HAVE_SIGALTSTACK` guard even though it does not have `SA_ONSTACK` set in its `sa_flags`. Maybe we can move it outside?

**Comment by cpitclaudel** [comment]
Hmm, strange.  I `#ifdef`'d it out becuase it depends on `segv_handler`, which depends on the stack base address set up by `sigaltstack`. 

I think that's a pre-existing bug, in fact, which should probably be fixed in a separate commit/PR.  The current code says:

```
   struct sigaction act4;
   act4.sa_sigaction = segv_handler; ← That looks wrong
   act4.sa_flags = SA_SIGINFO;
   sigemptyset(&act4.sa_mask);
   if(sigaction(SIGILL, &act4, NULL)) {
     throw Exception(string("sigaction(SIGILL) failure: ") + strerror(errno));
   }
```

Shouldn't that be `act4.sa_sigaction = ill_handler;` instead? [ill_handler](https://github.com/cpitclaudel/CVC4/blob/master/src/main/util.cpp#L152) seems unused right now.

**Comment by 4tXJ7f** [comment]
Great catch, I submitted a pull request for this (#173).

**Comment by cpitclaudel** [comment]
Super; I'll update this PR after your is merged.

**Comment by 4tXJ7f** [comment]
PR has been merged :)

**Comment by cpitclaudel** [comment]
Thanks; updated.  The diff looks a bit silly, because I flipped the sigill and sigsegv handlers.

**Comment by cpitclaudel** [comment]
Ok, green build :)

**Pull request merged**
