### PR TITLE
Replace HistogramStat by IntegralHistogramStat

### PR DESCRIPTION
**Pull request by nafur**
This PR uses IntegralHistogramStat instead of HistogramStat when appropriate, that is everywhere.

### CODE REVIEW

**Comment by aniemetz** [comment]
Does this mean that HistogramStat is now obsolete?

**Comment by nafur** [comment]
> Does this mean that HistogramStat is now obsolete?

I think so, yes.

**Review by mpreiner — APPROVED** [review]
If `HistogramStat` is not used anymore then we can maybe delete it (unless it will be useful in the future).

**Comment by nafur** [comment]
> If `HistogramStat` is not used anymore then we can maybe delete it (unless it will be useful in the future).

I'll remove it for now. After all, reimplementing it if we need it at some point is not that difficult...

**Pull request merged**
