### PR TITLE
Add isParameterized function to Expr

### PR DESCRIPTION
**Pull request by ajreynol**
This fixes a bug in the sygus v2 parser where we were creating invalid Expr, in particular for BV extract terms.

AFAIK, there was a limitation where term conversions could not be applied in a generic way to Expr since it was not clear when the operator needed to passed back to `mkExpr`.  At the Node level, the check for this case is `getMetaKind() == kind::metakind::PARAMETERIZED`.  This makes this check available in Expr as a function `isParameterized()`.

@barrettcw this may be of interest to you.

### CODE REVIEW

**Comment by ajreynol** [comment]
You mean add `isParameterized` to the new API?

It looks as though the new API is missing a number of related functions from Expr, including `getOperator`.  Perhaps we need a discussion to ensure we carry over the necessary functions from Expr to Term?

**Comment by aniemetz** [comment]
Yeah, it probably misses functionality that was added recently. This should all be exported to the new API.

**Comment by aniemetz** [comment]
For now, it would be great if you added this one already on this PR, and for the rest we could discuss how to proceed in the meeting tomorrow.

**Comment by ajreynol** [comment]
I've added it to the API.

The unit test I would add would involve the functionality I discussed (re-constructing a node based on its children), however, this will only be possible once there is a way to do `getOperator`.

**Comment by ajreynol** [comment]
Opened: https://github.com/CVC4/CVC4/issues/3314.

**Pull request merged**
