### PR TITLE
Storing a std::pair<Key,Data> on CDOhash_map. 

### PR DESCRIPTION
**Pull request by timothy-king**
Changing the return type of CDHashMap::iterator* to return a reference. Requires performance testing.

### CODE REVIEW

**Comment by timothy-king** [comment]
It would also be good to subject this to ASAN.

**Comment by barrettcw** [comment]
Yeah - let's let nightly build take care of that.

-Clark

**Comment by timothy-king** [comment]
@mpreiner and @barrettcw I am a bit confused about what the plan is now. Are we going to wait on performance tests and an ASAN run or some combination of these two?

**Comment by mpreiner** [comment]
I'll make a cluster run soon and report results here. Until then this PR should not get merged in.

**Comment by mpreiner** [comment]
ASAN does not report any errors.

**Comment by mpreiner** [comment]
Here are the results for the cluster runs for each version on all incremental benchmarks (3 runs per version, 1200s timeout):

```
   RUN |      SLVD |       SAT |    UNSAT |    CPU[s] |  SPACE[MB] |   
base-1 |  16176679 |  13376850 |  2799796 |  587163.0 |   934993.5 |            
base-2 |  16116405 |  13319201 |  2797171 |  586737.0 |   935911.8 |            
base-3 |  16257322 |  13453706 |  2803583 |  586542.1 |   935605.4 |            
 new-1 |  16302942 |  13486800 |  2816109 |  587021.4 |   934770.6 |            
 new-2 |  16313670 |  13507535 |  2806102 |  586797.8 |   933028.1 |                                                   
 new-3 |  16255620 |  13447233 |  2808354 |  586780.0 |   933599.5 |
```

**Comment by timothy-king** [comment]
I think those numbers are good. Should we go forward with the change?

**Comment by mpreiner** [comment]
Yes let's get this PR in :-)

**Pull request merged**
