### PR TITLE
Add subdirectories to contrib for competition scripts

### PR DESCRIPTION
**Pull request by ajreynol**
The `contrib/` folder is overcrowded with competition scripts, this PR organizes this.

### CODE REVIEW

**Comment by ajreynol** [comment]
I've updated the directory structure based on the suggestion.

**Comment by mpreiner** [comment]
How about dropping the `Comp` for smt and sygus since it is in the `competitions` directory?

**Comment by ajreynol** [comment]
I think I prefer the Comp there since it is accurate to the competition name (e.g. what if there was another kind of sygus comp?)

**Comment by mpreiner** [comment]
Ok, how about `sygus-comp` and `smt-comp` then? :)

**Comment by ajreynol** [comment]
Haha sure. All this coding lately has gotten me into using camel case for everything :)

**Pull request merged**
