### PR TITLE
Fix issue #1074, improve non-fatal error handling

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Commit 54d24c786d6a843cc72dfb5e377603349ea5e420 was
changing CVC4 to handle certain non-fatal errors
(such as calling get-unsat-core without a proceding
unsat check-sat command) without terminating the
solver. In the case of get-unsat-cores, the changes
lead to the solver crashing because it was trying to
print an unsat core initialized with the default
constructor, so the member variable d_smt was NULL,
which lead to a dereference of a null pointer.

One of the issues of the way non-fatal errors were
handled was that the error reporting was done in the
invoke() method of the command instead of the
printResult() method, which lead to the error
described above and other issues such as a call to
get-value printing a value after reporting an error.

This commit aims to improve the design by adding a
RecoverableModalException for errors that the solver
can recover from and CommandRecoverableFailure to
communicate that a command failed in a way that does
not prohibit the solver from continuing to execute.
The exception RecoverableModalException is thrown by
the SMTEngine and the commands catch it and turn it
into a CommandRecoverableFailure. The commit changes
all error conditions from the commit above and adds a
regression test for them.

Fixes issue #1074.

### CODE REVIEW

**Comment by ajreynol** [comment]
I personally dislike Exceptions, hence I would prefer to fix the code in the callers of these functions e.g. calling getUnsatCore always gives you an unsat core object but it is up to the caller to check if it is a valid object.

But I'd if we are okay with using Exceptions, this commit looks okay to me.

**Comment by 4tXJ7f** [comment]
I am not a huge fan of exceptions myself---I'd actually prefer if the SmtEngine methods returned a CommandStatus---but I tried to mirror existing code. If you'd always get an unsat core object, it would be difficult for the caller to determine why the call failed. Returning a CommandStatus together with the unsat core object would get around that limitation. Both approaches would change how the API works at a pretty fundamental level, so we should probably discuss whether we want such a thing at one of the meetings.

**Comment by timothy-king** [comment]
I think aiming to simplify these contracts makes sense. Part of the problem with this approach is that it requires a fairly sophisticated user to be able to use these contracts correctly. They need to be able to distinguish between "ModalException, TypeCheckingException, LogicException, UnsafeInterruptException" then distinguish between Modal and RecoverableModal exceptions to do the correct catch at run time. Who would have happened to have read that detail? I think the contract may need to be a bit more obvious. (Note: I will not be able to attend the next meeting.)

**Comment by 4tXJ7f** [comment]
I agree, we need an API that is simple to use but can provide more details if needed. One way could be to have two types of SmtEngineStatus (SmtEngineSuccess, SmtEngineFailure) that the SmtEngine returns for methods such as getValue/getUnsatCore/etc. SmtEngineFailure could then have fields for the reason and maybe a boolean whether continuing to use the solver is safe. This definitely needs some thought and discussion though. Also, while preparing this PR, I realized that everything related to Commands is littered with `dynamic_cast`s, which we should probably tackle at some point, too.

**Comment by timothy-king** [comment]
I think the suggestion is a good one. Basically a Maybe where nothing corresponds to an error message and maybe an enum to identify the error. It will take quite a bit of design. I think it would make sense to fix the issue at hand, open a new issue to come back to the longer term problem, and add comment like "// TODO(#N): Problem description" where N is the issue number. Unfortunately, looking ahead a lot of those TODOs should be things like "delete recoverable exception". (Yeah... not great.) If you are okay with also following up like this, I'm fine with going forward with this solution.

**Comment by 4tXJ7f** [comment]
@timothy-king I have added comments referring to issue #1108.

**Pull request merged**
